// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package fileresourceservice

import (
	"context"

	"go-zero-admin/application/applet/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FileIDRequest        = pb.FileIDRequest
	FileListRequest      = pb.FileListRequest
	FileListResponse     = pb.FileListResponse
	FileReferenceRequest = pb.FileReferenceRequest
	FileResource         = pb.FileResource
	NoDataResponse       = pb.NoDataResponse
	PageRequest          = pb.PageRequest
	RegisterFileRequest  = pb.RegisterFileRequest
	SessionRequest       = pb.SessionRequest

	FileResourceService interface {
		RegisterFile(ctx context.Context, in *RegisterFileRequest, opts ...grpc.CallOption) (*FileResource, error)
		GetFileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileListResponse, error)
		GetFile(ctx context.Context, in *FileIDRequest, opts ...grpc.CallOption) (*FileResource, error)
		AddFileReference(ctx context.Context, in *FileReferenceRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		RemoveFileReference(ctx context.Context, in *FileReferenceRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		BeginDeleteFile(ctx context.Context, in *FileIDRequest, opts ...grpc.CallOption) (*FileResource, error)
		FinishDeleteFile(ctx context.Context, in *FileIDRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	}

	defaultFileResourceService struct {
		cli zrpc.Client
	}
)

func NewFileResourceService(cli zrpc.Client) FileResourceService {
	return &defaultFileResourceService{
		cli: cli,
	}
}

func (m *defaultFileResourceService) RegisterFile(ctx context.Context, in *RegisterFileRequest, opts ...grpc.CallOption) (*FileResource, error) {
	client := pb.NewFileResourceServiceClient(m.cli.Conn())
	return client.RegisterFile(ctx, in, opts...)
}

func (m *defaultFileResourceService) GetFileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileListResponse, error) {
	client := pb.NewFileResourceServiceClient(m.cli.Conn())
	return client.GetFileList(ctx, in, opts...)
}

func (m *defaultFileResourceService) GetFile(ctx context.Context, in *FileIDRequest, opts ...grpc.CallOption) (*FileResource, error) {
	client := pb.NewFileResourceServiceClient(m.cli.Conn())
	return client.GetFile(ctx, in, opts...)
}

func (m *defaultFileResourceService) AddFileReference(ctx context.Context, in *FileReferenceRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewFileResourceServiceClient(m.cli.Conn())
	return client.AddFileReference(ctx, in, opts...)
}

func (m *defaultFileResourceService) RemoveFileReference(ctx context.Context, in *FileReferenceRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewFileResourceServiceClient(m.cli.Conn())
	return client.RemoveFileReference(ctx, in, opts...)
}

func (m *defaultFileResourceService) BeginDeleteFile(ctx context.Context, in *FileIDRequest, opts ...grpc.CallOption) (*FileResource, error) {
	client := pb.NewFileResourceServiceClient(m.cli.Conn())
	return client.BeginDeleteFile(ctx, in, opts...)
}

func (m *defaultFileResourceService) FinishDeleteFile(ctx context.Context, in *FileIDRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewFileResourceServiceClient(m.cli.Conn())
	return client.FinishDeleteFile(ctx, in, opts...)
}
