// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: ai.proto

package agent

import (
	"context"

	"go-zero-admin/application/ai/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentConversation             = pb.AgentConversation
	AgentConversationListResponse = pb.AgentConversationListResponse
	AgentIDRequest                = pb.AgentIDRequest
	AgentInfo                     = pb.AgentInfo
	AgentInfoRequest              = pb.AgentInfoRequest
	AgentMessage                  = pb.AgentMessage
	AgentMessageListRequest       = pb.AgentMessageListRequest
	AgentMessageListResponse      = pb.AgentMessageListResponse
	AgentPageRequest              = pb.AgentPageRequest
	AgentRun                      = pb.AgentRun
	AgentToolCall                 = pb.AgentToolCall
	AgentToolInfo                 = pb.AgentToolInfo
	CreateAgentRunRequest         = pb.CreateAgentRunRequest
	SessionRequest                = pb.SessionRequest

	Agent interface {
		GetAgentInfo(ctx context.Context, in *AgentInfoRequest, opts ...grpc.CallOption) (*AgentInfo, error)
		CreateAgentRun(ctx context.Context, in *CreateAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error)
		GetAgentRun(ctx context.Context, in *AgentIDRequest, opts ...grpc.CallOption) (*AgentRun, error)
		CancelAgentRun(ctx context.Context, in *AgentIDRequest, opts ...grpc.CallOption) (*AgentRun, error)
		ListAgentConversations(ctx context.Context, in *AgentPageRequest, opts ...grpc.CallOption) (*AgentConversationListResponse, error)
		ListAgentMessages(ctx context.Context, in *AgentMessageListRequest, opts ...grpc.CallOption) (*AgentMessageListResponse, error)
	}

	defaultAgent struct {
		cli zrpc.Client
	}
)

func NewAgent(cli zrpc.Client) Agent {
	return &defaultAgent{
		cli: cli,
	}
}

func (m *defaultAgent) GetAgentInfo(ctx context.Context, in *AgentInfoRequest, opts ...grpc.CallOption) (*AgentInfo, error) {
	client := pb.NewAgentClient(m.cli.Conn())
	return client.GetAgentInfo(ctx, in, opts...)
}

func (m *defaultAgent) CreateAgentRun(ctx context.Context, in *CreateAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error) {
	client := pb.NewAgentClient(m.cli.Conn())
	return client.CreateAgentRun(ctx, in, opts...)
}

func (m *defaultAgent) GetAgentRun(ctx context.Context, in *AgentIDRequest, opts ...grpc.CallOption) (*AgentRun, error) {
	client := pb.NewAgentClient(m.cli.Conn())
	return client.GetAgentRun(ctx, in, opts...)
}

func (m *defaultAgent) CancelAgentRun(ctx context.Context, in *AgentIDRequest, opts ...grpc.CallOption) (*AgentRun, error) {
	client := pb.NewAgentClient(m.cli.Conn())
	return client.CancelAgentRun(ctx, in, opts...)
}

func (m *defaultAgent) ListAgentConversations(ctx context.Context, in *AgentPageRequest, opts ...grpc.CallOption) (*AgentConversationListResponse, error) {
	client := pb.NewAgentClient(m.cli.Conn())
	return client.ListAgentConversations(ctx, in, opts...)
}

func (m *defaultAgent) ListAgentMessages(ctx context.Context, in *AgentMessageListRequest, opts ...grpc.CallOption) (*AgentMessageListResponse, error) {
	client := pb.NewAgentClient(m.cli.Conn())
	return client.ListAgentMessages(ctx, in, opts...)
}
