// Code generated by goctl. DO NOT EDIT.
// Source: applet.proto

package server

import (
	"context"

	"go-zero-admin/application/applet/rpc/internal/logic/dictionary"
	"go-zero-admin/application/applet/rpc/internal/svc"
	"go-zero-admin/application/applet/rpc/pb"
)

type DictionaryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDictionaryServer
}

func NewDictionaryServer(svcCtx *svc.ServiceContext) *DictionaryServer {
	return &DictionaryServer{
		svcCtx: svcCtx,
	}
}

// 获取SysDictionary列表
func (s *DictionaryServer) GetSysDictionaryList(ctx context.Context, in *pb.NoDataResponse) (*pb.DictionaryListResponse, error) {
	l := dictionarylogic.NewGetSysDictionaryListLogic(ctx, s.svcCtx)
	return l.GetSysDictionaryList(in)
}
