// Code generated by goctl. DO NOT EDIT.
// Source: applet.proto

package server

import (
	"context"

	"go-zero-admin/application/applet/rpc/internal/logic/dictionary"
	"go-zero-admin/application/applet/rpc/internal/svc"
	"go-zero-admin/application/applet/rpc/pb"
)

type DictionaryServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDictionaryServer
}

func NewDictionaryServer(svcCtx *svc.ServiceContext) *DictionaryServer {
	return &DictionaryServer{
		svcCtx: svcCtx,
	}
}

// 获取SysDictionary列表 -- all
func (s *DictionaryServer) GetSysDictionaryList(ctx context.Context, in *pb.NoDataResponse) (*pb.DictionaryListResponse, error) {
	l := dictionarylogic.NewGetSysDictionaryListLogic(ctx, s.svcCtx)
	return l.GetSysDictionaryList(in)
}

// 获取SysDictionaryInfo列表 -- 分页带搜索
func (s *DictionaryServer) GetSysDictionaryInfoList(ctx context.Context, in *pb.GetSysDictionaryInfoListRequest) (*pb.GetSysDictionaryInfoListResponse, error) {
	l := dictionarylogic.NewGetSysDictionaryInfoListLogic(ctx, s.svcCtx)
	return l.GetSysDictionaryInfoList(in)
}
