// Code generated by goctl. DO NOT EDIT.
// Source: applet.proto

package server

import (
	"context"

	"go-zero-admin/application/applet/rpc/internal/logic/api"
	"go-zero-admin/application/applet/rpc/internal/svc"
	"go-zero-admin/application/applet/rpc/pb"
)

type APIServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAPIServer
}

func NewAPIServer(svcCtx *svc.ServiceContext) *APIServer {
	return &APIServer{
		svcCtx: svcCtx,
	}
}

// 获取API列表
func (s *APIServer) GetApiList(ctx context.Context, in *pb.GetApiListRequest) (*pb.GetApiListResponse, error) {
	l := apilogic.NewGetApiListLogic(ctx, s.svcCtx)
	return l.GetApiList(in)
}

// 创建/添加 API列表
func (s *APIServer) CreateApi(ctx context.Context, in *pb.CreateApiRequest) (*pb.CreateApiResponse, error) {
	l := apilogic.NewCreateApiLogic(ctx, s.svcCtx)
	return l.CreateApi(in)
}

// 删除API列表
func (s *APIServer) DeleteApi(ctx context.Context, in *pb.DeleteApiRequest) (*pb.DeleteApiResponse, error) {
	l := apilogic.NewDeleteApiLogic(ctx, s.svcCtx)
	return l.DeleteApi(in)
}

// 获取全部API列表
func (s *APIServer) GetAllApiList(ctx context.Context, in *pb.GetAllApiListRequest) (*pb.GetAllApiListResponse, error) {
	l := apilogic.NewGetAllApiListLogic(ctx, s.svcCtx)
	return l.GetAllApiList(in)
}
