// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package api

import (
	"context"

	"go-zero-admin/application/applet/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateApiRequest       = pb.CreateApiRequest
	DeleteApiRequest       = pb.DeleteApiRequest
	DeleteApisByIdsRequest = pb.DeleteApisByIdsRequest
	GetAllApiListResponse  = pb.GetAllApiListResponse
	GetApiListRequest      = pb.GetApiListRequest
	GetApiListResponse     = pb.GetApiListResponse
	NoDataResponse         = pb.NoDataResponse
	PageRequest            = pb.PageRequest
	SysApi                 = pb.SysApi
	UpdateApiRequest       = pb.UpdateApiRequest

	Api interface {
		// 获取API列表
		GetApiList(ctx context.Context, in *GetApiListRequest, opts ...grpc.CallOption) (*GetApiListResponse, error)
		// 创建/添加 API列表
		CreateApi(ctx context.Context, in *CreateApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		// 删除API列表
		DeleteApi(ctx context.Context, in *DeleteApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		// 获取全部API列表
		GetAllApiList(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*GetAllApiListResponse, error)
		// 删除多条api
		DeleteApisByIds(ctx context.Context, in *DeleteApisByIdsRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		// 更新api
		UpdateApi(ctx context.Context, in *UpdateApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	}

	defaultApi struct {
		cli zrpc.Client
	}
)

func NewApi(cli zrpc.Client) Api {
	return &defaultApi{
		cli: cli,
	}
}

// 获取API列表
func (m *defaultApi) GetApiList(ctx context.Context, in *GetApiListRequest, opts ...grpc.CallOption) (*GetApiListResponse, error) {
	client := pb.NewApiClient(m.cli.Conn())
	return client.GetApiList(ctx, in, opts...)
}

// 创建/添加 API列表
func (m *defaultApi) CreateApi(ctx context.Context, in *CreateApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewApiClient(m.cli.Conn())
	return client.CreateApi(ctx, in, opts...)
}

// 删除API列表
func (m *defaultApi) DeleteApi(ctx context.Context, in *DeleteApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewApiClient(m.cli.Conn())
	return client.DeleteApi(ctx, in, opts...)
}

// 获取全部API列表
func (m *defaultApi) GetAllApiList(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*GetAllApiListResponse, error) {
	client := pb.NewApiClient(m.cli.Conn())
	return client.GetAllApiList(ctx, in, opts...)
}

// 删除多条api
func (m *defaultApi) DeleteApisByIds(ctx context.Context, in *DeleteApisByIdsRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewApiClient(m.cli.Conn())
	return client.DeleteApisByIds(ctx, in, opts...)
}

// 更新api
func (m *defaultApi) UpdateApi(ctx context.Context, in *UpdateApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewApiClient(m.cli.Conn())
	return client.UpdateApi(ctx, in, opts...)
}
