// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.1
// source: application/applet/rpc/desc/applet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_CheckSession_FullMethodName          = "/pb.User/CheckSession"
	User_GetCurrentUser_FullMethodName        = "/pb.User/GetCurrentUser"
	User_ChangePassword_FullMethodName        = "/pb.User/ChangePassword"
	User_Logout_FullMethodName                = "/pb.User/Logout"
	User_GetUserInfo_FullMethodName           = "/pb.User/GetUserInfo"
	User_GetUserToke_FullMethodName           = "/pb.User/GetUserToke"
	User_GetUserList_FullMethodName           = "/pb.User/GetUserList"
	User_Register_FullMethodName              = "/pb.User/Register"
	User_UpdateUserInfo_FullMethodName        = "/pb.User/UpdateUserInfo"
	User_UpdateUserAuthorities_FullMethodName = "/pb.User/UpdateUserAuthorities"
	User_ResetUserPassword_FullMethodName     = "/pb.User/ResetUserPassword"
	User_DeleteUser_FullMethodName            = "/pb.User/DeleteUser"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	CheckSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*CheckSessionResponse, error)
	GetCurrentUser(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	Logout(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 获取用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	// 获取Token
	GetUserToke(ctx context.Context, in *GetUserTokeRequest, opts ...grpc.CallOption) (*GetUserTokeResponse, error)
	// 分页获取用户列表
	GetUserList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error)
	// 新增（注册）用户 - 管理员
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 修改用户信息
	UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 修改用户和角色的关系信息 -- 和上  在修改用户信息的时候请求
	UpdateUserAuthorities(ctx context.Context, in *UpdateUserAuthoritiesRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 重置用户密码 默认密码：goZero
	ResetUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 删除用户
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) CheckSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*CheckSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSessionResponse)
	err := c.cc.Invoke(ctx, User_CheckSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetCurrentUser(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, User_GetCurrentUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, User_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Logout(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, User_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, User_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserToke(ctx context.Context, in *GetUserTokeRequest, opts ...grpc.CallOption) (*GetUserTokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTokeResponse)
	err := c.cc.Invoke(ctx, User_GetUserToke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserList(ctx context.Context, in *GetUserListRequest, opts ...grpc.CallOption) (*GetUserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserListResponse)
	err := c.cc.Invoke(ctx, User_GetUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, User_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, User_UpdateUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUserAuthorities(ctx context.Context, in *UpdateUserAuthoritiesRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, User_UpdateUserAuthorities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ResetUserPassword(ctx context.Context, in *ResetUserPasswordRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, User_ResetUserPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, User_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	CheckSession(context.Context, *SessionRequest) (*CheckSessionResponse, error)
	GetCurrentUser(context.Context, *SessionRequest) (*GetUserInfoResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*NoDataResponse, error)
	Logout(context.Context, *SessionRequest) (*NoDataResponse, error)
	// 获取用户信息
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	// 获取Token
	GetUserToke(context.Context, *GetUserTokeRequest) (*GetUserTokeResponse, error)
	// 分页获取用户列表
	GetUserList(context.Context, *GetUserListRequest) (*GetUserListResponse, error)
	// 新增（注册）用户 - 管理员
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 修改用户信息
	UpdateUserInfo(context.Context, *UpdateUserInfoRequest) (*NoDataResponse, error)
	// 修改用户和角色的关系信息 -- 和上  在修改用户信息的时候请求
	UpdateUserAuthorities(context.Context, *UpdateUserAuthoritiesRequest) (*NoDataResponse, error)
	// 重置用户密码 默认密码：goZero
	ResetUserPassword(context.Context, *ResetUserPasswordRequest) (*NoDataResponse, error)
	// 删除用户
	DeleteUser(context.Context, *DeleteUserRequest) (*NoDataResponse, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) CheckSession(context.Context, *SessionRequest) (*CheckSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSession not implemented")
}
func (UnimplementedUserServer) GetCurrentUser(context.Context, *SessionRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentUser not implemented")
}
func (UnimplementedUserServer) ChangePassword(context.Context, *ChangePasswordRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedUserServer) Logout(context.Context, *SessionRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedUserServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserServer) GetUserToke(context.Context, *GetUserTokeRequest) (*GetUserTokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserToke not implemented")
}
func (UnimplementedUserServer) GetUserList(context.Context, *GetUserListRequest) (*GetUserListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserList not implemented")
}
func (UnimplementedUserServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserServer) UpdateUserInfo(context.Context, *UpdateUserInfoRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserInfo not implemented")
}
func (UnimplementedUserServer) UpdateUserAuthorities(context.Context, *UpdateUserAuthoritiesRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserAuthorities not implemented")
}
func (UnimplementedUserServer) ResetUserPassword(context.Context, *ResetUserPasswordRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetUserPassword not implemented")
}
func (UnimplementedUserServer) DeleteUser(context.Context, *DeleteUserRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call panics, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_CheckSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CheckSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CheckSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CheckSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetCurrentUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCurrentUser(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Logout(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserToke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserToke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserToke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserToke(ctx, req.(*GetUserTokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserList(ctx, req.(*GetUserListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUserInfo(ctx, req.(*UpdateUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUserAuthorities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAuthoritiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUserAuthorities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateUserAuthorities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUserAuthorities(ctx, req.(*UpdateUserAuthoritiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ResetUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ResetUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_ResetUserPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ResetUserPassword(ctx, req.(*ResetUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckSession",
			Handler:    _User_CheckSession_Handler,
		},
		{
			MethodName: "GetCurrentUser",
			Handler:    _User_GetCurrentUser_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _User_ChangePassword_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _User_Logout_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _User_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUserToke",
			Handler:    _User_GetUserToke_Handler,
		},
		{
			MethodName: "GetUserList",
			Handler:    _User_GetUserList_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "UpdateUserInfo",
			Handler:    _User_UpdateUserInfo_Handler,
		},
		{
			MethodName: "UpdateUserAuthorities",
			Handler:    _User_UpdateUserAuthorities_Handler,
		},
		{
			MethodName: "ResetUserPassword",
			Handler:    _User_ResetUserPassword_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _User_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/applet/rpc/desc/applet.proto",
}

const (
	Menu_GetAuthorityButtons_FullMethodName    = "/pb.Menu/GetAuthorityButtons"
	Menu_UpdateAuthorityButtons_FullMethodName = "/pb.Menu/UpdateAuthorityButtons"
	Menu_GetMenuTree_FullMethodName            = "/pb.Menu/GetMenuTree"
	Menu_GetMenuBaseInfoList_FullMethodName    = "/pb.Menu/GetMenuBaseInfoList"
	Menu_AddMenuBase_FullMethodName            = "/pb.Menu/AddMenuBase"
	Menu_GetBaseMenuTree_FullMethodName        = "/pb.Menu/GetBaseMenuTree"
	Menu_GetMenuAuthority_FullMethodName       = "/pb.Menu/GetMenuAuthority"
	Menu_GetBaseMenuById_FullMethodName        = "/pb.Menu/GetBaseMenuById"
	Menu_UpdateBaseMenu_FullMethodName         = "/pb.Menu/UpdateBaseMenu"
	Menu_DeleteBaseMenu_FullMethodName         = "/pb.Menu/DeleteBaseMenu"
)

// MenuClient is the client API for Menu service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MenuClient interface {
	GetAuthorityButtons(ctx context.Context, in *GetAuthorityButtonsRequest, opts ...grpc.CallOption) (*GetAuthorityButtonsResponse, error)
	UpdateAuthorityButtons(ctx context.Context, in *UpdateAuthorityButtonsRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 获取菜单-路由
	GetMenuTree(ctx context.Context, in *GetMenuTreeRequest, opts ...grpc.CallOption) (*GetMenuTreeResponse, error)
	// 获取系统基础菜单列表
	GetMenuBaseInfoList(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*GetMenuBaseInfoListResponse, error)
	// 添加系统基础菜单列表
	AddMenuBase(ctx context.Context, in *AddMenuBaseRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 获取用户动态路由树  -- 用于角色管理的设置权限
	GetBaseMenuTree(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*GetBaseMenuTreeResponse, error)
	// 获取指定角色menu  -- 用于角色管理的设置权限
	GetMenuAuthority(ctx context.Context, in *GetMenuAuthorityRequest, opts ...grpc.CallOption) (*GetMenuAuthorityResponse, error)
	// 根据id获取系统菜单
	GetBaseMenuById(ctx context.Context, in *GetBaseMenuByIdRequest, opts ...grpc.CallOption) (*GetBaseMenuByIdResponse, error)
	// 更新系统菜单
	UpdateBaseMenu(ctx context.Context, in *UpdateBaseMenuRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 删除系统菜单
	DeleteBaseMenu(ctx context.Context, in *DeleteBaseMenuRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
}

type menuClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuClient(cc grpc.ClientConnInterface) MenuClient {
	return &menuClient{cc}
}

func (c *menuClient) GetAuthorityButtons(ctx context.Context, in *GetAuthorityButtonsRequest, opts ...grpc.CallOption) (*GetAuthorityButtonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthorityButtonsResponse)
	err := c.cc.Invoke(ctx, Menu_GetAuthorityButtons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) UpdateAuthorityButtons(ctx context.Context, in *UpdateAuthorityButtonsRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Menu_UpdateAuthorityButtons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetMenuTree(ctx context.Context, in *GetMenuTreeRequest, opts ...grpc.CallOption) (*GetMenuTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMenuTreeResponse)
	err := c.cc.Invoke(ctx, Menu_GetMenuTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetMenuBaseInfoList(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*GetMenuBaseInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMenuBaseInfoListResponse)
	err := c.cc.Invoke(ctx, Menu_GetMenuBaseInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) AddMenuBase(ctx context.Context, in *AddMenuBaseRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Menu_AddMenuBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetBaseMenuTree(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*GetBaseMenuTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBaseMenuTreeResponse)
	err := c.cc.Invoke(ctx, Menu_GetBaseMenuTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetMenuAuthority(ctx context.Context, in *GetMenuAuthorityRequest, opts ...grpc.CallOption) (*GetMenuAuthorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMenuAuthorityResponse)
	err := c.cc.Invoke(ctx, Menu_GetMenuAuthority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetBaseMenuById(ctx context.Context, in *GetBaseMenuByIdRequest, opts ...grpc.CallOption) (*GetBaseMenuByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBaseMenuByIdResponse)
	err := c.cc.Invoke(ctx, Menu_GetBaseMenuById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) UpdateBaseMenu(ctx context.Context, in *UpdateBaseMenuRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Menu_UpdateBaseMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) DeleteBaseMenu(ctx context.Context, in *DeleteBaseMenuRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Menu_DeleteBaseMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuServer is the server API for Menu service.
// All implementations must embed UnimplementedMenuServer
// for forward compatibility.
type MenuServer interface {
	GetAuthorityButtons(context.Context, *GetAuthorityButtonsRequest) (*GetAuthorityButtonsResponse, error)
	UpdateAuthorityButtons(context.Context, *UpdateAuthorityButtonsRequest) (*NoDataResponse, error)
	// 获取菜单-路由
	GetMenuTree(context.Context, *GetMenuTreeRequest) (*GetMenuTreeResponse, error)
	// 获取系统基础菜单列表
	GetMenuBaseInfoList(context.Context, *NoDataResponse) (*GetMenuBaseInfoListResponse, error)
	// 添加系统基础菜单列表
	AddMenuBase(context.Context, *AddMenuBaseRequest) (*NoDataResponse, error)
	// 获取用户动态路由树  -- 用于角色管理的设置权限
	GetBaseMenuTree(context.Context, *NoDataResponse) (*GetBaseMenuTreeResponse, error)
	// 获取指定角色menu  -- 用于角色管理的设置权限
	GetMenuAuthority(context.Context, *GetMenuAuthorityRequest) (*GetMenuAuthorityResponse, error)
	// 根据id获取系统菜单
	GetBaseMenuById(context.Context, *GetBaseMenuByIdRequest) (*GetBaseMenuByIdResponse, error)
	// 更新系统菜单
	UpdateBaseMenu(context.Context, *UpdateBaseMenuRequest) (*NoDataResponse, error)
	// 删除系统菜单
	DeleteBaseMenu(context.Context, *DeleteBaseMenuRequest) (*NoDataResponse, error)
	mustEmbedUnimplementedMenuServer()
}

// UnimplementedMenuServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMenuServer struct{}

func (UnimplementedMenuServer) GetAuthorityButtons(context.Context, *GetAuthorityButtonsRequest) (*GetAuthorityButtonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorityButtons not implemented")
}
func (UnimplementedMenuServer) UpdateAuthorityButtons(context.Context, *UpdateAuthorityButtonsRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAuthorityButtons not implemented")
}
func (UnimplementedMenuServer) GetMenuTree(context.Context, *GetMenuTreeRequest) (*GetMenuTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenuTree not implemented")
}
func (UnimplementedMenuServer) GetMenuBaseInfoList(context.Context, *NoDataResponse) (*GetMenuBaseInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenuBaseInfoList not implemented")
}
func (UnimplementedMenuServer) AddMenuBase(context.Context, *AddMenuBaseRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMenuBase not implemented")
}
func (UnimplementedMenuServer) GetBaseMenuTree(context.Context, *NoDataResponse) (*GetBaseMenuTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBaseMenuTree not implemented")
}
func (UnimplementedMenuServer) GetMenuAuthority(context.Context, *GetMenuAuthorityRequest) (*GetMenuAuthorityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenuAuthority not implemented")
}
func (UnimplementedMenuServer) GetBaseMenuById(context.Context, *GetBaseMenuByIdRequest) (*GetBaseMenuByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBaseMenuById not implemented")
}
func (UnimplementedMenuServer) UpdateBaseMenu(context.Context, *UpdateBaseMenuRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBaseMenu not implemented")
}
func (UnimplementedMenuServer) DeleteBaseMenu(context.Context, *DeleteBaseMenuRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBaseMenu not implemented")
}
func (UnimplementedMenuServer) mustEmbedUnimplementedMenuServer() {}
func (UnimplementedMenuServer) testEmbeddedByValue()              {}

// UnsafeMenuServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MenuServer will
// result in compilation errors.
type UnsafeMenuServer interface {
	mustEmbedUnimplementedMenuServer()
}

func RegisterMenuServer(s grpc.ServiceRegistrar, srv MenuServer) {
	// If the following call panics, it indicates UnimplementedMenuServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Menu_ServiceDesc, srv)
}

func _Menu_GetAuthorityButtons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorityButtonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetAuthorityButtons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_GetAuthorityButtons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetAuthorityButtons(ctx, req.(*GetAuthorityButtonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_UpdateAuthorityButtons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAuthorityButtonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).UpdateAuthorityButtons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_UpdateAuthorityButtons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).UpdateAuthorityButtons(ctx, req.(*UpdateAuthorityButtonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetMenuTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetMenuTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_GetMenuTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetMenuTree(ctx, req.(*GetMenuTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetMenuBaseInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoDataResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetMenuBaseInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_GetMenuBaseInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetMenuBaseInfoList(ctx, req.(*NoDataResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_AddMenuBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMenuBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).AddMenuBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_AddMenuBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).AddMenuBase(ctx, req.(*AddMenuBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetBaseMenuTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoDataResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetBaseMenuTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_GetBaseMenuTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetBaseMenuTree(ctx, req.(*NoDataResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetMenuAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuAuthorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetMenuAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_GetMenuAuthority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetMenuAuthority(ctx, req.(*GetMenuAuthorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetBaseMenuById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaseMenuByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetBaseMenuById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_GetBaseMenuById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetBaseMenuById(ctx, req.(*GetBaseMenuByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_UpdateBaseMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBaseMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).UpdateBaseMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_UpdateBaseMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).UpdateBaseMenu(ctx, req.(*UpdateBaseMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_DeleteBaseMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBaseMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).DeleteBaseMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Menu_DeleteBaseMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).DeleteBaseMenu(ctx, req.(*DeleteBaseMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Menu_ServiceDesc is the grpc.ServiceDesc for Menu service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Menu_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Menu",
	HandlerType: (*MenuServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthorityButtons",
			Handler:    _Menu_GetAuthorityButtons_Handler,
		},
		{
			MethodName: "UpdateAuthorityButtons",
			Handler:    _Menu_UpdateAuthorityButtons_Handler,
		},
		{
			MethodName: "GetMenuTree",
			Handler:    _Menu_GetMenuTree_Handler,
		},
		{
			MethodName: "GetMenuBaseInfoList",
			Handler:    _Menu_GetMenuBaseInfoList_Handler,
		},
		{
			MethodName: "AddMenuBase",
			Handler:    _Menu_AddMenuBase_Handler,
		},
		{
			MethodName: "GetBaseMenuTree",
			Handler:    _Menu_GetBaseMenuTree_Handler,
		},
		{
			MethodName: "GetMenuAuthority",
			Handler:    _Menu_GetMenuAuthority_Handler,
		},
		{
			MethodName: "GetBaseMenuById",
			Handler:    _Menu_GetBaseMenuById_Handler,
		},
		{
			MethodName: "UpdateBaseMenu",
			Handler:    _Menu_UpdateBaseMenu_Handler,
		},
		{
			MethodName: "DeleteBaseMenu",
			Handler:    _Menu_DeleteBaseMenu_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/applet/rpc/desc/applet.proto",
}

const (
	Authority_GetAuthorityList_FullMethodName = "/pb.Authority/GetAuthorityList"
	Authority_AddAuthorityMenu_FullMethodName = "/pb.Authority/AddAuthorityMenu"
	Authority_UpdateAuthority_FullMethodName  = "/pb.Authority/UpdateAuthority"
	Authority_CreateAuthority_FullMethodName  = "/pb.Authority/CreateAuthority"
	Authority_DeleteAuthority_FullMethodName  = "/pb.Authority/DeleteAuthority"
)

// AuthorityClient is the client API for Authority service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorityClient interface {
	// 获取角色列表
	GetAuthorityList(ctx context.Context, in *GetAuthorityListRequest, opts ...grpc.CallOption) (*GetAuthorityListResponse, error)
	// 增加base_menu和角色关联关系 -- 用于角色管理的设置权限
	AddAuthorityMenu(ctx context.Context, in *AddAuthorityMenuRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 更新角色 -- 设为首页
	UpdateAuthority(ctx context.Context, in *UpdateAuthorityRequest, opts ...grpc.CallOption) (*UpdateAuthorityResponse, error)
	// 创建角色
	CreateAuthority(ctx context.Context, in *CreateAuthorityRequest, opts ...grpc.CallOption) (*CreateAuthorityResponse, error)
	// 删除角色
	DeleteAuthority(ctx context.Context, in *DeleteAuthorityRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
}

type authorityClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorityClient(cc grpc.ClientConnInterface) AuthorityClient {
	return &authorityClient{cc}
}

func (c *authorityClient) GetAuthorityList(ctx context.Context, in *GetAuthorityListRequest, opts ...grpc.CallOption) (*GetAuthorityListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthorityListResponse)
	err := c.cc.Invoke(ctx, Authority_GetAuthorityList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorityClient) AddAuthorityMenu(ctx context.Context, in *AddAuthorityMenuRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Authority_AddAuthorityMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorityClient) UpdateAuthority(ctx context.Context, in *UpdateAuthorityRequest, opts ...grpc.CallOption) (*UpdateAuthorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAuthorityResponse)
	err := c.cc.Invoke(ctx, Authority_UpdateAuthority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorityClient) CreateAuthority(ctx context.Context, in *CreateAuthorityRequest, opts ...grpc.CallOption) (*CreateAuthorityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAuthorityResponse)
	err := c.cc.Invoke(ctx, Authority_CreateAuthority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorityClient) DeleteAuthority(ctx context.Context, in *DeleteAuthorityRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Authority_DeleteAuthority_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorityServer is the server API for Authority service.
// All implementations must embed UnimplementedAuthorityServer
// for forward compatibility.
type AuthorityServer interface {
	// 获取角色列表
	GetAuthorityList(context.Context, *GetAuthorityListRequest) (*GetAuthorityListResponse, error)
	// 增加base_menu和角色关联关系 -- 用于角色管理的设置权限
	AddAuthorityMenu(context.Context, *AddAuthorityMenuRequest) (*NoDataResponse, error)
	// 更新角色 -- 设为首页
	UpdateAuthority(context.Context, *UpdateAuthorityRequest) (*UpdateAuthorityResponse, error)
	// 创建角色
	CreateAuthority(context.Context, *CreateAuthorityRequest) (*CreateAuthorityResponse, error)
	// 删除角色
	DeleteAuthority(context.Context, *DeleteAuthorityRequest) (*NoDataResponse, error)
	mustEmbedUnimplementedAuthorityServer()
}

// UnimplementedAuthorityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorityServer struct{}

func (UnimplementedAuthorityServer) GetAuthorityList(context.Context, *GetAuthorityListRequest) (*GetAuthorityListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorityList not implemented")
}
func (UnimplementedAuthorityServer) AddAuthorityMenu(context.Context, *AddAuthorityMenuRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAuthorityMenu not implemented")
}
func (UnimplementedAuthorityServer) UpdateAuthority(context.Context, *UpdateAuthorityRequest) (*UpdateAuthorityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAuthority not implemented")
}
func (UnimplementedAuthorityServer) CreateAuthority(context.Context, *CreateAuthorityRequest) (*CreateAuthorityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuthority not implemented")
}
func (UnimplementedAuthorityServer) DeleteAuthority(context.Context, *DeleteAuthorityRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAuthority not implemented")
}
func (UnimplementedAuthorityServer) mustEmbedUnimplementedAuthorityServer() {}
func (UnimplementedAuthorityServer) testEmbeddedByValue()                   {}

// UnsafeAuthorityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorityServer will
// result in compilation errors.
type UnsafeAuthorityServer interface {
	mustEmbedUnimplementedAuthorityServer()
}

func RegisterAuthorityServer(s grpc.ServiceRegistrar, srv AuthorityServer) {
	// If the following call panics, it indicates UnimplementedAuthorityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Authority_ServiceDesc, srv)
}

func _Authority_GetAuthorityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorityListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorityServer).GetAuthorityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authority_GetAuthorityList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorityServer).GetAuthorityList(ctx, req.(*GetAuthorityListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authority_AddAuthorityMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAuthorityMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorityServer).AddAuthorityMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authority_AddAuthorityMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorityServer).AddAuthorityMenu(ctx, req.(*AddAuthorityMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authority_UpdateAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAuthorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorityServer).UpdateAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authority_UpdateAuthority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorityServer).UpdateAuthority(ctx, req.(*UpdateAuthorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authority_CreateAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorityServer).CreateAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authority_CreateAuthority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorityServer).CreateAuthority(ctx, req.(*CreateAuthorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authority_DeleteAuthority_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAuthorityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorityServer).DeleteAuthority(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Authority_DeleteAuthority_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorityServer).DeleteAuthority(ctx, req.(*DeleteAuthorityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Authority_ServiceDesc is the grpc.ServiceDesc for Authority service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Authority_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Authority",
	HandlerType: (*AuthorityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthorityList",
			Handler:    _Authority_GetAuthorityList_Handler,
		},
		{
			MethodName: "AddAuthorityMenu",
			Handler:    _Authority_AddAuthorityMenu_Handler,
		},
		{
			MethodName: "UpdateAuthority",
			Handler:    _Authority_UpdateAuthority_Handler,
		},
		{
			MethodName: "CreateAuthority",
			Handler:    _Authority_CreateAuthority_Handler,
		},
		{
			MethodName: "DeleteAuthority",
			Handler:    _Authority_DeleteAuthority_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/applet/rpc/desc/applet.proto",
}

const (
	Api_PreviewApiSync_FullMethodName  = "/pb.Api/PreviewApiSync"
	Api_ApplyApiSync_FullMethodName    = "/pb.Api/ApplyApiSync"
	Api_GetApiList_FullMethodName      = "/pb.Api/GetApiList"
	Api_CreateApi_FullMethodName       = "/pb.Api/CreateApi"
	Api_DeleteApi_FullMethodName       = "/pb.Api/DeleteApi"
	Api_GetAllApiList_FullMethodName   = "/pb.Api/GetAllApiList"
	Api_DeleteApisByIds_FullMethodName = "/pb.Api/DeleteApisByIds"
	Api_UpdateApi_FullMethodName       = "/pb.Api/UpdateApi"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	// 预览当前Swagger与权限资源的差异
	PreviewApiSync(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*PreviewApiSyncResponse, error)
	// 按已确认的差异同步资源，不修改现有授权
	ApplyApiSync(ctx context.Context, in *ApplyApiSyncRequest, opts ...grpc.CallOption) (*ApplyApiSyncResponse, error)
	// 获取API列表
	GetApiList(ctx context.Context, in *GetApiListRequest, opts ...grpc.CallOption) (*GetApiListResponse, error)
	// 创建/添加 API列表
	CreateApi(ctx context.Context, in *CreateApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 删除API列表
	DeleteApi(ctx context.Context, in *DeleteApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 获取全部API列表
	GetAllApiList(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*GetAllApiListResponse, error)
	// 删除多条api
	DeleteApisByIds(ctx context.Context, in *DeleteApisByIdsRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 更新api
	UpdateApi(ctx context.Context, in *UpdateApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) PreviewApiSync(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*PreviewApiSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewApiSyncResponse)
	err := c.cc.Invoke(ctx, Api_PreviewApiSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ApplyApiSync(ctx context.Context, in *ApplyApiSyncRequest, opts ...grpc.CallOption) (*ApplyApiSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyApiSyncResponse)
	err := c.cc.Invoke(ctx, Api_ApplyApiSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetApiList(ctx context.Context, in *GetApiListRequest, opts ...grpc.CallOption) (*GetApiListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApiListResponse)
	err := c.cc.Invoke(ctx, Api_GetApiList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CreateApi(ctx context.Context, in *CreateApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Api_CreateApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) DeleteApi(ctx context.Context, in *DeleteApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Api_DeleteApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetAllApiList(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*GetAllApiListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllApiListResponse)
	err := c.cc.Invoke(ctx, Api_GetAllApiList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) DeleteApisByIds(ctx context.Context, in *DeleteApisByIdsRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Api_DeleteApisByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UpdateApi(ctx context.Context, in *UpdateApiRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Api_UpdateApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility.
type ApiServer interface {
	// 预览当前Swagger与权限资源的差异
	PreviewApiSync(context.Context, *NoDataResponse) (*PreviewApiSyncResponse, error)
	// 按已确认的差异同步资源，不修改现有授权
	ApplyApiSync(context.Context, *ApplyApiSyncRequest) (*ApplyApiSyncResponse, error)
	// 获取API列表
	GetApiList(context.Context, *GetApiListRequest) (*GetApiListResponse, error)
	// 创建/添加 API列表
	CreateApi(context.Context, *CreateApiRequest) (*NoDataResponse, error)
	// 删除API列表
	DeleteApi(context.Context, *DeleteApiRequest) (*NoDataResponse, error)
	// 获取全部API列表
	GetAllApiList(context.Context, *NoDataResponse) (*GetAllApiListResponse, error)
	// 删除多条api
	DeleteApisByIds(context.Context, *DeleteApisByIdsRequest) (*NoDataResponse, error)
	// 更新api
	UpdateApi(context.Context, *UpdateApiRequest) (*NoDataResponse, error)
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) PreviewApiSync(context.Context, *NoDataResponse) (*PreviewApiSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewApiSync not implemented")
}
func (UnimplementedApiServer) ApplyApiSync(context.Context, *ApplyApiSyncRequest) (*ApplyApiSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyApiSync not implemented")
}
func (UnimplementedApiServer) GetApiList(context.Context, *GetApiListRequest) (*GetApiListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApiList not implemented")
}
func (UnimplementedApiServer) CreateApi(context.Context, *CreateApiRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApi not implemented")
}
func (UnimplementedApiServer) DeleteApi(context.Context, *DeleteApiRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteApi not implemented")
}
func (UnimplementedApiServer) GetAllApiList(context.Context, *NoDataResponse) (*GetAllApiListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllApiList not implemented")
}
func (UnimplementedApiServer) DeleteApisByIds(context.Context, *DeleteApisByIdsRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteApisByIds not implemented")
}
func (UnimplementedApiServer) UpdateApi(context.Context, *UpdateApiRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApi not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}
func (UnimplementedApiServer) testEmbeddedByValue()             {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call panics, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_PreviewApiSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoDataResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).PreviewApiSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_PreviewApiSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).PreviewApiSync(ctx, req.(*NoDataResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ApplyApiSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyApiSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ApplyApiSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_ApplyApiSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ApplyApiSync(ctx, req.(*ApplyApiSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetApiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApiListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetApiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetApiList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetApiList(ctx, req.(*GetApiListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CreateApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CreateApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_CreateApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CreateApi(ctx, req.(*CreateApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_DeleteApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).DeleteApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_DeleteApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).DeleteApi(ctx, req.(*DeleteApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetAllApiList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoDataResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetAllApiList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetAllApiList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetAllApiList(ctx, req.(*NoDataResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_DeleteApisByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApisByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).DeleteApisByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_DeleteApisByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).DeleteApisByIds(ctx, req.(*DeleteApisByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UpdateApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UpdateApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_UpdateApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UpdateApi(ctx, req.(*UpdateApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreviewApiSync",
			Handler:    _Api_PreviewApiSync_Handler,
		},
		{
			MethodName: "ApplyApiSync",
			Handler:    _Api_ApplyApiSync_Handler,
		},
		{
			MethodName: "GetApiList",
			Handler:    _Api_GetApiList_Handler,
		},
		{
			MethodName: "CreateApi",
			Handler:    _Api_CreateApi_Handler,
		},
		{
			MethodName: "DeleteApi",
			Handler:    _Api_DeleteApi_Handler,
		},
		{
			MethodName: "GetAllApiList",
			Handler:    _Api_GetAllApiList_Handler,
		},
		{
			MethodName: "DeleteApisByIds",
			Handler:    _Api_DeleteApisByIds_Handler,
		},
		{
			MethodName: "UpdateApi",
			Handler:    _Api_UpdateApi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/applet/rpc/desc/applet.proto",
}

const (
	Casbin_GetPathByAuthorityId_FullMethodName     = "/pb.Casbin/GetPathByAuthorityId"
	Casbin_UpdateCasbinData_FullMethodName         = "/pb.Casbin/UpdateCasbinData"
	Casbin_UpdateCasbinDataByApiIds_FullMethodName = "/pb.Casbin/UpdateCasbinDataByApiIds"
	Casbin_Enforce_FullMethodName                  = "/pb.Casbin/Enforce"
)

// CasbinClient is the client API for Casbin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CasbinClient interface {
	// 根据角色id获取对应的casbin数据
	GetPathByAuthorityId(ctx context.Context, in *GetPathByAuthorityIdRequest, opts ...grpc.CallOption) (*GetPathByAuthorityIdResponse, error)
	// 更新一个角色的对应的casbin数据
	UpdateCasbinData(ctx context.Context, in *UpdateCasbinDataRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 更新一个角色的对应的casbin数据 用api的ids 查数据
	//
	//	rpc UpdateCasbinDataByApiIds (UpdateCasbinDataByApiIdsRequest) returns (NoDataResponse);
	UpdateCasbinDataByApiIds(ctx context.Context, in *UpdateCasbinDataByApiIdsRequest, opts ...grpc.CallOption) (*UpdateCasbinDataByApiIdsResponse, error)
	// casbin 鉴权 供api网关/中间件调用
	Enforce(ctx context.Context, in *EnforceRequest, opts ...grpc.CallOption) (*EnforceResponse, error)
}

type casbinClient struct {
	cc grpc.ClientConnInterface
}

func NewCasbinClient(cc grpc.ClientConnInterface) CasbinClient {
	return &casbinClient{cc}
}

func (c *casbinClient) GetPathByAuthorityId(ctx context.Context, in *GetPathByAuthorityIdRequest, opts ...grpc.CallOption) (*GetPathByAuthorityIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPathByAuthorityIdResponse)
	err := c.cc.Invoke(ctx, Casbin_GetPathByAuthorityId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) UpdateCasbinData(ctx context.Context, in *UpdateCasbinDataRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Casbin_UpdateCasbinData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) UpdateCasbinDataByApiIds(ctx context.Context, in *UpdateCasbinDataByApiIdsRequest, opts ...grpc.CallOption) (*UpdateCasbinDataByApiIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCasbinDataByApiIdsResponse)
	err := c.cc.Invoke(ctx, Casbin_UpdateCasbinDataByApiIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *casbinClient) Enforce(ctx context.Context, in *EnforceRequest, opts ...grpc.CallOption) (*EnforceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnforceResponse)
	err := c.cc.Invoke(ctx, Casbin_Enforce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CasbinServer is the server API for Casbin service.
// All implementations must embed UnimplementedCasbinServer
// for forward compatibility.
type CasbinServer interface {
	// 根据角色id获取对应的casbin数据
	GetPathByAuthorityId(context.Context, *GetPathByAuthorityIdRequest) (*GetPathByAuthorityIdResponse, error)
	// 更新一个角色的对应的casbin数据
	UpdateCasbinData(context.Context, *UpdateCasbinDataRequest) (*NoDataResponse, error)
	// 更新一个角色的对应的casbin数据 用api的ids 查数据
	//
	//	rpc UpdateCasbinDataByApiIds (UpdateCasbinDataByApiIdsRequest) returns (NoDataResponse);
	UpdateCasbinDataByApiIds(context.Context, *UpdateCasbinDataByApiIdsRequest) (*UpdateCasbinDataByApiIdsResponse, error)
	// casbin 鉴权 供api网关/中间件调用
	Enforce(context.Context, *EnforceRequest) (*EnforceResponse, error)
	mustEmbedUnimplementedCasbinServer()
}

// UnimplementedCasbinServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCasbinServer struct{}

func (UnimplementedCasbinServer) GetPathByAuthorityId(context.Context, *GetPathByAuthorityIdRequest) (*GetPathByAuthorityIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPathByAuthorityId not implemented")
}
func (UnimplementedCasbinServer) UpdateCasbinData(context.Context, *UpdateCasbinDataRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCasbinData not implemented")
}
func (UnimplementedCasbinServer) UpdateCasbinDataByApiIds(context.Context, *UpdateCasbinDataByApiIdsRequest) (*UpdateCasbinDataByApiIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCasbinDataByApiIds not implemented")
}
func (UnimplementedCasbinServer) Enforce(context.Context, *EnforceRequest) (*EnforceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enforce not implemented")
}
func (UnimplementedCasbinServer) mustEmbedUnimplementedCasbinServer() {}
func (UnimplementedCasbinServer) testEmbeddedByValue()                {}

// UnsafeCasbinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CasbinServer will
// result in compilation errors.
type UnsafeCasbinServer interface {
	mustEmbedUnimplementedCasbinServer()
}

func RegisterCasbinServer(s grpc.ServiceRegistrar, srv CasbinServer) {
	// If the following call panics, it indicates UnimplementedCasbinServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Casbin_ServiceDesc, srv)
}

func _Casbin_GetPathByAuthorityId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPathByAuthorityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CasbinServer).GetPathByAuthorityId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Casbin_GetPathByAuthorityId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CasbinServer).GetPathByAuthorityId(ctx, req.(*GetPathByAuthorityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Casbin_UpdateCasbinData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCasbinDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CasbinServer).UpdateCasbinData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Casbin_UpdateCasbinData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CasbinServer).UpdateCasbinData(ctx, req.(*UpdateCasbinDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Casbin_UpdateCasbinDataByApiIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCasbinDataByApiIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CasbinServer).UpdateCasbinDataByApiIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Casbin_UpdateCasbinDataByApiIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CasbinServer).UpdateCasbinDataByApiIds(ctx, req.(*UpdateCasbinDataByApiIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Casbin_Enforce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnforceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CasbinServer).Enforce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Casbin_Enforce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CasbinServer).Enforce(ctx, req.(*EnforceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Casbin_ServiceDesc is the grpc.ServiceDesc for Casbin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Casbin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Casbin",
	HandlerType: (*CasbinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPathByAuthorityId",
			Handler:    _Casbin_GetPathByAuthorityId_Handler,
		},
		{
			MethodName: "UpdateCasbinData",
			Handler:    _Casbin_UpdateCasbinData_Handler,
		},
		{
			MethodName: "UpdateCasbinDataByApiIds",
			Handler:    _Casbin_UpdateCasbinDataByApiIds_Handler,
		},
		{
			MethodName: "Enforce",
			Handler:    _Casbin_Enforce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/applet/rpc/desc/applet.proto",
}

const (
	Dictionary_GetSysDictionaryList_FullMethodName                = "/pb.Dictionary/GetSysDictionaryList"
	Dictionary_CreateSysDictionary_FullMethodName                 = "/pb.Dictionary/CreateSysDictionary"
	Dictionary_GetSysDictionaryDetails_FullMethodName             = "/pb.Dictionary/GetSysDictionaryDetails"
	Dictionary_UpdateSysDictionary_FullMethodName                 = "/pb.Dictionary/UpdateSysDictionary"
	Dictionary_DeleteSysDictionary_FullMethodName                 = "/pb.Dictionary/DeleteSysDictionary"
	Dictionary_GetSysDictionaryInfoList_FullMethodName            = "/pb.Dictionary/GetSysDictionaryInfoList"
	Dictionary_GetSysDictionaryInfoListDetailsById_FullMethodName = "/pb.Dictionary/GetSysDictionaryInfoListDetailsById"
	Dictionary_UpdateSysDictionaryInfo_FullMethodName             = "/pb.Dictionary/UpdateSysDictionaryInfo"
	Dictionary_CreateSysDictionaryInfo_FullMethodName             = "/pb.Dictionary/CreateSysDictionaryInfo"
	Dictionary_DeleteSysDictionaryInfo_FullMethodName             = "/pb.Dictionary/DeleteSysDictionaryInfo"
)

// DictionaryClient is the client API for Dictionary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DictionaryClient interface {
	// 获取SysDictionary列表 -- all
	GetSysDictionaryList(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*DictionaryListResponse, error)
	// 新建SysDictionary
	CreateSysDictionary(ctx context.Context, in *CreateSysDictionaryRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 根据ID或者type获取SysDictionary
	GetSysDictionaryDetails(ctx context.Context, in *GetSysDictionaryDetailsRequest, opts ...grpc.CallOption) (*GetSysDictionaryDetailsResponse, error)
	// 更新SysDictionary
	UpdateSysDictionary(ctx context.Context, in *UpdateSysDictionaryRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 更新SysDictionary
	DeleteSysDictionary(ctx context.Context, in *DeleteSysDictionaryRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 获取SysDictionaryInfo列表 -- 分页带搜索
	GetSysDictionaryInfoList(ctx context.Context, in *GetSysDictionaryInfoListRequest, opts ...grpc.CallOption) (*GetSysDictionaryInfoListResponse, error)
	// 根据id获取SysDictionaryInfo详情
	GetSysDictionaryInfoListDetailsById(ctx context.Context, in *GetSysDictionaryInfoListDetailsByIdRequest, opts ...grpc.CallOption) (*GetSysDictionaryInfoListDetailsByIdResponse, error)
	// 更新SysDictionaryInfo
	UpdateSysDictionaryInfo(ctx context.Context, in *UpdateSysDictionaryInfoRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 创建SysDictionaryInfo
	CreateSysDictionaryInfo(ctx context.Context, in *CreateSysDictionaryInfoRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	// 删除SysDictionaryInfo
	DeleteSysDictionaryInfo(ctx context.Context, in *DeleteSysDictionaryInfoRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
}

type dictionaryClient struct {
	cc grpc.ClientConnInterface
}

func NewDictionaryClient(cc grpc.ClientConnInterface) DictionaryClient {
	return &dictionaryClient{cc}
}

func (c *dictionaryClient) GetSysDictionaryList(ctx context.Context, in *NoDataResponse, opts ...grpc.CallOption) (*DictionaryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictionaryListResponse)
	err := c.cc.Invoke(ctx, Dictionary_GetSysDictionaryList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) CreateSysDictionary(ctx context.Context, in *CreateSysDictionaryRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Dictionary_CreateSysDictionary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) GetSysDictionaryDetails(ctx context.Context, in *GetSysDictionaryDetailsRequest, opts ...grpc.CallOption) (*GetSysDictionaryDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSysDictionaryDetailsResponse)
	err := c.cc.Invoke(ctx, Dictionary_GetSysDictionaryDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) UpdateSysDictionary(ctx context.Context, in *UpdateSysDictionaryRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Dictionary_UpdateSysDictionary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) DeleteSysDictionary(ctx context.Context, in *DeleteSysDictionaryRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Dictionary_DeleteSysDictionary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) GetSysDictionaryInfoList(ctx context.Context, in *GetSysDictionaryInfoListRequest, opts ...grpc.CallOption) (*GetSysDictionaryInfoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSysDictionaryInfoListResponse)
	err := c.cc.Invoke(ctx, Dictionary_GetSysDictionaryInfoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) GetSysDictionaryInfoListDetailsById(ctx context.Context, in *GetSysDictionaryInfoListDetailsByIdRequest, opts ...grpc.CallOption) (*GetSysDictionaryInfoListDetailsByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSysDictionaryInfoListDetailsByIdResponse)
	err := c.cc.Invoke(ctx, Dictionary_GetSysDictionaryInfoListDetailsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) UpdateSysDictionaryInfo(ctx context.Context, in *UpdateSysDictionaryInfoRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Dictionary_UpdateSysDictionaryInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) CreateSysDictionaryInfo(ctx context.Context, in *CreateSysDictionaryInfoRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Dictionary_CreateSysDictionaryInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictionaryClient) DeleteSysDictionaryInfo(ctx context.Context, in *DeleteSysDictionaryInfoRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoDataResponse)
	err := c.cc.Invoke(ctx, Dictionary_DeleteSysDictionaryInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictionaryServer is the server API for Dictionary service.
// All implementations must embed UnimplementedDictionaryServer
// for forward compatibility.
type DictionaryServer interface {
	// 获取SysDictionary列表 -- all
	GetSysDictionaryList(context.Context, *NoDataResponse) (*DictionaryListResponse, error)
	// 新建SysDictionary
	CreateSysDictionary(context.Context, *CreateSysDictionaryRequest) (*NoDataResponse, error)
	// 根据ID或者type获取SysDictionary
	GetSysDictionaryDetails(context.Context, *GetSysDictionaryDetailsRequest) (*GetSysDictionaryDetailsResponse, error)
	// 更新SysDictionary
	UpdateSysDictionary(context.Context, *UpdateSysDictionaryRequest) (*NoDataResponse, error)
	// 更新SysDictionary
	DeleteSysDictionary(context.Context, *DeleteSysDictionaryRequest) (*NoDataResponse, error)
	// 获取SysDictionaryInfo列表 -- 分页带搜索
	GetSysDictionaryInfoList(context.Context, *GetSysDictionaryInfoListRequest) (*GetSysDictionaryInfoListResponse, error)
	// 根据id获取SysDictionaryInfo详情
	GetSysDictionaryInfoListDetailsById(context.Context, *GetSysDictionaryInfoListDetailsByIdRequest) (*GetSysDictionaryInfoListDetailsByIdResponse, error)
	// 更新SysDictionaryInfo
	UpdateSysDictionaryInfo(context.Context, *UpdateSysDictionaryInfoRequest) (*NoDataResponse, error)
	// 创建SysDictionaryInfo
	CreateSysDictionaryInfo(context.Context, *CreateSysDictionaryInfoRequest) (*NoDataResponse, error)
	// 删除SysDictionaryInfo
	DeleteSysDictionaryInfo(context.Context, *DeleteSysDictionaryInfoRequest) (*NoDataResponse, error)
	mustEmbedUnimplementedDictionaryServer()
}

// UnimplementedDictionaryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDictionaryServer struct{}

func (UnimplementedDictionaryServer) GetSysDictionaryList(context.Context, *NoDataResponse) (*DictionaryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSysDictionaryList not implemented")
}
func (UnimplementedDictionaryServer) CreateSysDictionary(context.Context, *CreateSysDictionaryRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSysDictionary not implemented")
}
func (UnimplementedDictionaryServer) GetSysDictionaryDetails(context.Context, *GetSysDictionaryDetailsRequest) (*GetSysDictionaryDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSysDictionaryDetails not implemented")
}
func (UnimplementedDictionaryServer) UpdateSysDictionary(context.Context, *UpdateSysDictionaryRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSysDictionary not implemented")
}
func (UnimplementedDictionaryServer) DeleteSysDictionary(context.Context, *DeleteSysDictionaryRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSysDictionary not implemented")
}
func (UnimplementedDictionaryServer) GetSysDictionaryInfoList(context.Context, *GetSysDictionaryInfoListRequest) (*GetSysDictionaryInfoListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSysDictionaryInfoList not implemented")
}
func (UnimplementedDictionaryServer) GetSysDictionaryInfoListDetailsById(context.Context, *GetSysDictionaryInfoListDetailsByIdRequest) (*GetSysDictionaryInfoListDetailsByIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSysDictionaryInfoListDetailsById not implemented")
}
func (UnimplementedDictionaryServer) UpdateSysDictionaryInfo(context.Context, *UpdateSysDictionaryInfoRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSysDictionaryInfo not implemented")
}
func (UnimplementedDictionaryServer) CreateSysDictionaryInfo(context.Context, *CreateSysDictionaryInfoRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSysDictionaryInfo not implemented")
}
func (UnimplementedDictionaryServer) DeleteSysDictionaryInfo(context.Context, *DeleteSysDictionaryInfoRequest) (*NoDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSysDictionaryInfo not implemented")
}
func (UnimplementedDictionaryServer) mustEmbedUnimplementedDictionaryServer() {}
func (UnimplementedDictionaryServer) testEmbeddedByValue()                    {}

// UnsafeDictionaryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DictionaryServer will
// result in compilation errors.
type UnsafeDictionaryServer interface {
	mustEmbedUnimplementedDictionaryServer()
}

func RegisterDictionaryServer(s grpc.ServiceRegistrar, srv DictionaryServer) {
	// If the following call panics, it indicates UnimplementedDictionaryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dictionary_ServiceDesc, srv)
}

func _Dictionary_GetSysDictionaryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoDataResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).GetSysDictionaryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_GetSysDictionaryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).GetSysDictionaryList(ctx, req.(*NoDataResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_CreateSysDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSysDictionaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).CreateSysDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_CreateSysDictionary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).CreateSysDictionary(ctx, req.(*CreateSysDictionaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_GetSysDictionaryDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSysDictionaryDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).GetSysDictionaryDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_GetSysDictionaryDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).GetSysDictionaryDetails(ctx, req.(*GetSysDictionaryDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_UpdateSysDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSysDictionaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).UpdateSysDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_UpdateSysDictionary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).UpdateSysDictionary(ctx, req.(*UpdateSysDictionaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_DeleteSysDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSysDictionaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).DeleteSysDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_DeleteSysDictionary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).DeleteSysDictionary(ctx, req.(*DeleteSysDictionaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_GetSysDictionaryInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSysDictionaryInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).GetSysDictionaryInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_GetSysDictionaryInfoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).GetSysDictionaryInfoList(ctx, req.(*GetSysDictionaryInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_GetSysDictionaryInfoListDetailsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSysDictionaryInfoListDetailsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).GetSysDictionaryInfoListDetailsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_GetSysDictionaryInfoListDetailsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).GetSysDictionaryInfoListDetailsById(ctx, req.(*GetSysDictionaryInfoListDetailsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_UpdateSysDictionaryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSysDictionaryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).UpdateSysDictionaryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_UpdateSysDictionaryInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).UpdateSysDictionaryInfo(ctx, req.(*UpdateSysDictionaryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_CreateSysDictionaryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSysDictionaryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).CreateSysDictionaryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_CreateSysDictionaryInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).CreateSysDictionaryInfo(ctx, req.(*CreateSysDictionaryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dictionary_DeleteSysDictionaryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSysDictionaryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictionaryServer).DeleteSysDictionaryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dictionary_DeleteSysDictionaryInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictionaryServer).DeleteSysDictionaryInfo(ctx, req.(*DeleteSysDictionaryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dictionary_ServiceDesc is the grpc.ServiceDesc for Dictionary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dictionary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Dictionary",
	HandlerType: (*DictionaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSysDictionaryList",
			Handler:    _Dictionary_GetSysDictionaryList_Handler,
		},
		{
			MethodName: "CreateSysDictionary",
			Handler:    _Dictionary_CreateSysDictionary_Handler,
		},
		{
			MethodName: "GetSysDictionaryDetails",
			Handler:    _Dictionary_GetSysDictionaryDetails_Handler,
		},
		{
			MethodName: "UpdateSysDictionary",
			Handler:    _Dictionary_UpdateSysDictionary_Handler,
		},
		{
			MethodName: "DeleteSysDictionary",
			Handler:    _Dictionary_DeleteSysDictionary_Handler,
		},
		{
			MethodName: "GetSysDictionaryInfoList",
			Handler:    _Dictionary_GetSysDictionaryInfoList_Handler,
		},
		{
			MethodName: "GetSysDictionaryInfoListDetailsById",
			Handler:    _Dictionary_GetSysDictionaryInfoListDetailsById_Handler,
		},
		{
			MethodName: "UpdateSysDictionaryInfo",
			Handler:    _Dictionary_UpdateSysDictionaryInfo_Handler,
		},
		{
			MethodName: "CreateSysDictionaryInfo",
			Handler:    _Dictionary_CreateSysDictionaryInfo_Handler,
		},
		{
			MethodName: "DeleteSysDictionaryInfo",
			Handler:    _Dictionary_DeleteSysDictionaryInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/applet/rpc/desc/applet.proto",
}
