// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package server

import (
	"context"

	"go-zero-admin/application/applet/rpc/internal/logic/permission"
	"go-zero-admin/application/applet/rpc/internal/svc"
	"go-zero-admin/application/applet/rpc/pb"
)

type PermissionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPermissionServer
}

func NewPermissionServer(svcCtx *svc.ServiceContext) *PermissionServer {
	return &PermissionServer{
		svcCtx: svcCtx,
	}
}

func (s *PermissionServer) GetPermissionEdit(ctx context.Context, in *pb.GetPermissionEditRequest) (*pb.GetPermissionEditResponse, error) {
	l := permissionlogic.NewGetPermissionEditLogic(ctx, s.svcCtx)
	return l.GetPermissionEdit(in)
}

func (s *PermissionServer) GetPermissionSnapshot(ctx context.Context, in *pb.GetPermissionSnapshotRequest) (*pb.GetPermissionSnapshotResponse, error) {
	l := permissionlogic.NewGetPermissionSnapshotLogic(ctx, s.svcCtx)
	return l.GetPermissionSnapshot(in)
}

func (s *PermissionServer) GetPermissionHistory(ctx context.Context, in *pb.GetPermissionHistoryRequest) (*pb.GetPermissionHistoryResponse, error) {
	l := permissionlogic.NewGetPermissionHistoryLogic(ctx, s.svcCtx)
	return l.GetPermissionHistory(in)
}

func (s *PermissionServer) PreviewPermissionRollback(ctx context.Context, in *pb.PreviewPermissionRollbackRequest) (*pb.PreviewPermissionRollbackResponse, error) {
	l := permissionlogic.NewPreviewPermissionRollbackLogic(ctx, s.svcCtx)
	return l.PreviewPermissionRollback(in)
}

func (s *PermissionServer) ApplyPermissionRollback(ctx context.Context, in *pb.ApplyPermissionRollbackRequest) (*pb.NoDataResponse, error) {
	l := permissionlogic.NewApplyPermissionRollbackLogic(ctx, s.svcCtx)
	return l.ApplyPermissionRollback(in)
}
