// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package server

import (
	"context"

	"go-zero-admin/application/applet/rpc/internal/logic/sessionmanage"
	"go-zero-admin/application/applet/rpc/internal/svc"
	"go-zero-admin/application/applet/rpc/pb"
)

type SessionManageServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSessionManageServer
}

func NewSessionManageServer(svcCtx *svc.ServiceContext) *SessionManageServer {
	return &SessionManageServer{
		svcCtx: svcCtx,
	}
}

func (s *SessionManageServer) GetDeviceSessions(ctx context.Context, in *pb.DeviceSessionListRequest) (*pb.DeviceSessionListResponse, error) {
	l := sessionmanagelogic.NewGetDeviceSessionsLogic(ctx, s.svcCtx)
	return l.GetDeviceSessions(in)
}

func (s *SessionManageServer) RevokeDeviceSession(ctx context.Context, in *pb.RevokeDeviceSessionRequest) (*pb.NoDataResponse, error) {
	l := sessionmanagelogic.NewRevokeDeviceSessionLogic(ctx, s.svcCtx)
	return l.RevokeDeviceSession(in)
}
