// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package server

import (
	"context"

	"go-zero-admin/application/applet/rpc/internal/logic/fileresourceservice"
	"go-zero-admin/application/applet/rpc/internal/svc"
	"go-zero-admin/application/applet/rpc/pb"
)

type FileResourceServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileResourceServiceServer
}

func NewFileResourceServiceServer(svcCtx *svc.ServiceContext) *FileResourceServiceServer {
	return &FileResourceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FileResourceServiceServer) RegisterFile(ctx context.Context, in *pb.RegisterFileRequest) (*pb.FileResource, error) {
	l := fileresourceservicelogic.NewRegisterFileLogic(ctx, s.svcCtx)
	return l.RegisterFile(in)
}

func (s *FileResourceServiceServer) GetFileList(ctx context.Context, in *pb.FileListRequest) (*pb.FileListResponse, error) {
	l := fileresourceservicelogic.NewGetFileListLogic(ctx, s.svcCtx)
	return l.GetFileList(in)
}

func (s *FileResourceServiceServer) GetFile(ctx context.Context, in *pb.FileIDRequest) (*pb.FileResource, error) {
	l := fileresourceservicelogic.NewGetFileLogic(ctx, s.svcCtx)
	return l.GetFile(in)
}

func (s *FileResourceServiceServer) AddFileReference(ctx context.Context, in *pb.FileReferenceRequest) (*pb.NoDataResponse, error) {
	l := fileresourceservicelogic.NewAddFileReferenceLogic(ctx, s.svcCtx)
	return l.AddFileReference(in)
}

func (s *FileResourceServiceServer) RemoveFileReference(ctx context.Context, in *pb.FileReferenceRequest) (*pb.NoDataResponse, error) {
	l := fileresourceservicelogic.NewRemoveFileReferenceLogic(ctx, s.svcCtx)
	return l.RemoveFileReference(in)
}

func (s *FileResourceServiceServer) BeginDeleteFile(ctx context.Context, in *pb.FileIDRequest) (*pb.FileResource, error) {
	l := fileresourceservicelogic.NewBeginDeleteFileLogic(ctx, s.svcCtx)
	return l.BeginDeleteFile(in)
}

func (s *FileResourceServiceServer) FinishDeleteFile(ctx context.Context, in *pb.FileIDRequest) (*pb.NoDataResponse, error) {
	l := fileresourceservicelogic.NewFinishDeleteFileLogic(ctx, s.svcCtx)
	return l.FinishDeleteFile(in)
}
