// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package permission

import (
	"context"

	"go-zero-admin/application/applet/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyPermissionRollbackRequest    = pb.ApplyPermissionRollbackRequest
	CasbinInfo                        = pb.CasbinInfo
	Department                        = pb.Department
	GetPermissionEditRequest          = pb.GetPermissionEditRequest
	GetPermissionEditResponse         = pb.GetPermissionEditResponse
	GetPermissionHistoryRequest       = pb.GetPermissionHistoryRequest
	GetPermissionHistoryResponse      = pb.GetPermissionHistoryResponse
	GetPermissionSnapshotRequest      = pb.GetPermissionSnapshotRequest
	GetPermissionSnapshotResponse     = pb.GetPermissionSnapshotResponse
	Meta                              = pb.Meta
	NoDataResponse                    = pb.NoDataResponse
	PageRequest                       = pb.PageRequest
	PermissionChange                  = pb.PermissionChange
	PermissionGrantSet                = pb.PermissionGrantSet
	PreviewPermissionRollbackRequest  = pb.PreviewPermissionRollbackRequest
	PreviewPermissionRollbackResponse = pb.PreviewPermissionRollbackResponse
	RoleDataScope                     = pb.RoleDataScope
	SessionRequest                    = pb.SessionRequest
	SysApi                            = pb.SysApi
	SysAuthority                      = pb.SysAuthority
	SysBaseMenu                       = pb.SysBaseMenu
	SysBaseMenuBtn                    = pb.SysBaseMenuBtn
	SysBaseMenuParameter              = pb.SysBaseMenuParameter
	SysMenu                           = pb.SysMenu

	Permission interface {
		GetPermissionEdit(ctx context.Context, in *GetPermissionEditRequest, opts ...grpc.CallOption) (*GetPermissionEditResponse, error)
		GetPermissionSnapshot(ctx context.Context, in *GetPermissionSnapshotRequest, opts ...grpc.CallOption) (*GetPermissionSnapshotResponse, error)
		GetPermissionHistory(ctx context.Context, in *GetPermissionHistoryRequest, opts ...grpc.CallOption) (*GetPermissionHistoryResponse, error)
		PreviewPermissionRollback(ctx context.Context, in *PreviewPermissionRollbackRequest, opts ...grpc.CallOption) (*PreviewPermissionRollbackResponse, error)
		ApplyPermissionRollback(ctx context.Context, in *ApplyPermissionRollbackRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	}

	defaultPermission struct {
		cli zrpc.Client
	}
)

func NewPermission(cli zrpc.Client) Permission {
	return &defaultPermission{
		cli: cli,
	}
}

func (m *defaultPermission) GetPermissionEdit(ctx context.Context, in *GetPermissionEditRequest, opts ...grpc.CallOption) (*GetPermissionEditResponse, error) {
	client := pb.NewPermissionClient(m.cli.Conn())
	return client.GetPermissionEdit(ctx, in, opts...)
}

func (m *defaultPermission) GetPermissionSnapshot(ctx context.Context, in *GetPermissionSnapshotRequest, opts ...grpc.CallOption) (*GetPermissionSnapshotResponse, error) {
	client := pb.NewPermissionClient(m.cli.Conn())
	return client.GetPermissionSnapshot(ctx, in, opts...)
}

func (m *defaultPermission) GetPermissionHistory(ctx context.Context, in *GetPermissionHistoryRequest, opts ...grpc.CallOption) (*GetPermissionHistoryResponse, error) {
	client := pb.NewPermissionClient(m.cli.Conn())
	return client.GetPermissionHistory(ctx, in, opts...)
}

func (m *defaultPermission) PreviewPermissionRollback(ctx context.Context, in *PreviewPermissionRollbackRequest, opts ...grpc.CallOption) (*PreviewPermissionRollbackResponse, error) {
	client := pb.NewPermissionClient(m.cli.Conn())
	return client.PreviewPermissionRollback(ctx, in, opts...)
}

func (m *defaultPermission) ApplyPermissionRollback(ctx context.Context, in *ApplyPermissionRollbackRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewPermissionClient(m.cli.Conn())
	return client.ApplyPermissionRollback(ctx, in, opts...)
}
