// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package agenttools

import (
	"context"

	"go-zero-admin/application/applet/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AgentToolRequest = pb.AgentToolRequest
	AgentToolResult  = pb.AgentToolResult
	SessionRequest   = pb.SessionRequest

	AgentTools interface {
		QueryAgentAudit(ctx context.Context, in *AgentToolRequest, opts ...grpc.CallOption) (*AgentToolResult, error)
		GetAgentFileStatus(ctx context.Context, in *AgentToolRequest, opts ...grpc.CallOption) (*AgentToolResult, error)
		ListAgentDevices(ctx context.Context, in *AgentToolRequest, opts ...grpc.CallOption) (*AgentToolResult, error)
	}

	defaultAgentTools struct {
		cli zrpc.Client
	}
)

func NewAgentTools(cli zrpc.Client) AgentTools {
	return &defaultAgentTools{
		cli: cli,
	}
}

func (m *defaultAgentTools) QueryAgentAudit(ctx context.Context, in *AgentToolRequest, opts ...grpc.CallOption) (*AgentToolResult, error) {
	client := pb.NewAgentToolsClient(m.cli.Conn())
	return client.QueryAgentAudit(ctx, in, opts...)
}

func (m *defaultAgentTools) GetAgentFileStatus(ctx context.Context, in *AgentToolRequest, opts ...grpc.CallOption) (*AgentToolResult, error) {
	client := pb.NewAgentToolsClient(m.cli.Conn())
	return client.GetAgentFileStatus(ctx, in, opts...)
}

func (m *defaultAgentTools) ListAgentDevices(ctx context.Context, in *AgentToolRequest, opts ...grpc.CallOption) (*AgentToolResult, error) {
	client := pb.NewAgentToolsClient(m.cli.Conn())
	return client.ListAgentDevices(ctx, in, opts...)
}
