// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.1
// source: application/ai/rpc/desc/ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Trusted identity comes from the authenticated API, not the model.
type SessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserID         int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SessionVersion int64                  `protobuf:"varint,2,opt,name=SessionVersion,proto3" json:"SessionVersion,omitempty"`
	AuthorityId    int64                  `protobuf:"varint,3,opt,name=AuthorityId,proto3" json:"AuthorityId,omitempty"`
	SessionID      string                 `protobuf:"bytes,4,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{0}
}

func (x *SessionRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SessionRequest) GetSessionVersion() int64 {
	if x != nil {
		return x.SessionVersion
	}
	return 0
}

func (x *SessionRequest) GetAuthorityId() int64 {
	if x != nil {
		return x.AuthorityId
	}
	return 0
}

func (x *SessionRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

// Async AI Agent. Actor comes from the authenticated API, never model arguments.
type AgentToolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=Label,proto3" json:"Label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Available     bool                   `protobuf:"varint,4,opt,name=Available,proto3" json:"Available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToolInfo) Reset() {
	*x = AgentToolInfo{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToolInfo) ProtoMessage() {}

func (x *AgentToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToolInfo.ProtoReflect.Descriptor instead.
func (*AgentToolInfo) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AgentToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentToolInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AgentToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentToolInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type AgentToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=Summary,proto3" json:"Summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToolCall) Reset() {
	*x = AgentToolCall{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToolCall) ProtoMessage() {}

func (x *AgentToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToolCall.ProtoReflect.Descriptor instead.
func (*AgentToolCall) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{2}
}

func (x *AgentToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentToolCall) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentToolCall) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentToolCall) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	Configured    bool                   `protobuf:"varint,2,opt,name=Configured,proto3" json:"Configured,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=Provider,proto3" json:"Provider,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=Model,proto3" json:"Model,omitempty"`
	Tools         []*AgentToolInfo       `protobuf:"bytes,5,rep,name=Tools,proto3" json:"Tools,omitempty"`
	MaxInputChars int64                  `protobuf:"varint,6,opt,name=MaxInputChars,proto3" json:"MaxInputChars,omitempty"`
	MaxSteps      int64                  `protobuf:"varint,7,opt,name=MaxSteps,proto3" json:"MaxSteps,omitempty"`
	MaxRunSeconds int64                  `protobuf:"varint,8,opt,name=MaxRunSeconds,proto3" json:"MaxRunSeconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AgentInfo) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *AgentInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentInfo) GetTools() []*AgentToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentInfo) GetMaxInputChars() int64 {
	if x != nil {
		return x.MaxInputChars
	}
	return 0
}

func (x *AgentInfo) GetMaxSteps() int64 {
	if x != nil {
		return x.MaxSteps
	}
	return 0
}

func (x *AgentInfo) GetMaxRunSeconds() int64 {
	if x != nil {
		return x.MaxRunSeconds
	}
	return 0
}

type AgentRun struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=ConversationId,proto3" json:"ConversationId,omitempty"`
	RequestId      string                 `protobuf:"bytes,3,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Answer         string                 `protobuf:"bytes,5,opt,name=Answer,proto3" json:"Answer,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=Error,proto3" json:"Error,omitempty"`
	Provider       string                 `protobuf:"bytes,7,opt,name=Provider,proto3" json:"Provider,omitempty"`
	Model          string                 `protobuf:"bytes,8,opt,name=Model,proto3" json:"Model,omitempty"`
	InputTokens    int64                  `protobuf:"varint,9,opt,name=InputTokens,proto3" json:"InputTokens,omitempty"`
	OutputTokens   int64                  `protobuf:"varint,10,opt,name=OutputTokens,proto3" json:"OutputTokens,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,12,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ToolCalls      []*AgentToolCall       `protobuf:"bytes,13,rep,name=ToolCalls,proto3" json:"ToolCalls,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRun) Reset() {
	*x = AgentRun{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRun) ProtoMessage() {}

func (x *AgentRun) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRun.ProtoReflect.Descriptor instead.
func (*AgentRun) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AgentRun) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AgentRun) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentRun) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentRun) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AgentRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentRun) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AgentRun) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentRun) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *AgentRun) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *AgentRun) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AgentRun) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AgentRun) GetToolCalls() []*AgentToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type AgentConversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConversation) Reset() {
	*x = AgentConversation{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConversation) ProtoMessage() {}

func (x *AgentConversation) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConversation.ProtoReflect.Descriptor instead.
func (*AgentConversation) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{5}
}

func (x *AgentConversation) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AgentConversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AgentConversation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AgentConversation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AgentMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=ConversationId,proto3" json:"ConversationId,omitempty"`
	RunId          string                 `protobuf:"bytes,3,opt,name=RunId,proto3" json:"RunId,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=Role,proto3" json:"Role,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{6}
}

func (x *AgentMessage) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AgentMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *AgentMessage) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AgentInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *SessionRequest        `protobuf:"bytes,1,opt,name=Actor,proto3" json:"Actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfoRequest) Reset() {
	*x = AgentInfoRequest{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfoRequest) ProtoMessage() {}

func (x *AgentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfoRequest.ProtoReflect.Descriptor instead.
func (*AgentInfoRequest) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{7}
}

func (x *AgentInfoRequest) GetActor() *SessionRequest {
	if x != nil {
		return x.Actor
	}
	return nil
}

type CreateAgentRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Actor          *SessionRequest        `protobuf:"bytes,1,opt,name=Actor,proto3" json:"Actor,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=ConversationId,proto3" json:"ConversationId,omitempty"`
	RequestId      string                 `protobuf:"bytes,3,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAgentRunRequest) Reset() {
	*x = CreateAgentRunRequest{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRunRequest) ProtoMessage() {}

func (x *CreateAgentRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRunRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRunRequest) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAgentRunRequest) GetActor() *SessionRequest {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *CreateAgentRunRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CreateAgentRunRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateAgentRunRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AgentIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *SessionRequest        `protobuf:"bytes,1,opt,name=Actor,proto3" json:"Actor,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIDRequest) Reset() {
	*x = AgentIDRequest{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIDRequest) ProtoMessage() {}

func (x *AgentIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIDRequest.ProtoReflect.Descriptor instead.
func (*AgentIDRequest) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{9}
}

func (x *AgentIDRequest) GetActor() *SessionRequest {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AgentIDRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type AgentPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *SessionRequest        `protobuf:"bytes,1,opt,name=Actor,proto3" json:"Actor,omitempty"`
	PageNo        int64                  `protobuf:"varint,2,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentPageRequest) Reset() {
	*x = AgentPageRequest{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentPageRequest) ProtoMessage() {}

func (x *AgentPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentPageRequest.ProtoReflect.Descriptor instead.
func (*AgentPageRequest) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{10}
}

func (x *AgentPageRequest) GetActor() *SessionRequest {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AgentPageRequest) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *AgentPageRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AgentMessageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *SessionRequest        `protobuf:"bytes,1,opt,name=Actor,proto3" json:"Actor,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	PageNo        int64                  `protobuf:"varint,3,opt,name=PageNo,proto3" json:"PageNo,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessageListRequest) Reset() {
	*x = AgentMessageListRequest{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessageListRequest) ProtoMessage() {}

func (x *AgentMessageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessageListRequest.ProtoReflect.Descriptor instead.
func (*AgentMessageListRequest) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{11}
}

func (x *AgentMessageListRequest) GetActor() *SessionRequest {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AgentMessageListRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AgentMessageListRequest) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *AgentMessageListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AgentConversationListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AgentConversation   `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConversationListResponse) Reset() {
	*x = AgentConversationListResponse{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConversationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConversationListResponse) ProtoMessage() {}

func (x *AgentConversationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConversationListResponse.ProtoReflect.Descriptor instead.
func (*AgentConversationListResponse) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{12}
}

func (x *AgentConversationListResponse) GetItems() []*AgentConversation {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AgentConversationListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AgentMessageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AgentMessage        `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessageListResponse) Reset() {
	*x = AgentMessageListResponse{}
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessageListResponse) ProtoMessage() {}

func (x *AgentMessageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_ai_rpc_desc_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessageListResponse.ProtoReflect.Descriptor instead.
func (*AgentMessageListResponse) Descriptor() ([]byte, []int) {
	return file_application_ai_rpc_desc_ai_proto_rawDescGZIP(), []int{13}
}

func (x *AgentMessageListResponse) GetItems() []*AgentMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AgentMessageListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_application_ai_rpc_desc_ai_proto protoreflect.FileDescriptor

const file_application_ai_rpc_desc_ai_proto_rawDesc = "" +
	"\n" +
	" application/ai/rpc/desc/ai.proto\x12\x02ai\"\x90\x01\n" +
	"\x0eSessionRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\x12&\n" +
	"\x0eSessionVersion\x18\x02 \x01(\x03R\x0eSessionVersion\x12 \n" +
	"\vAuthorityId\x18\x03 \x01(\x03R\vAuthorityId\x12\x1c\n" +
	"\tSessionID\x18\x04 \x01(\tR\tSessionID\"y\n" +
	"\rAgentToolInfo\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Label\x18\x02 \x01(\tR\x05Label\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1c\n" +
	"\tAvailable\x18\x04 \x01(\bR\tAvailable\"k\n" +
	"\rAgentToolCall\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\tR\x06Status\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\x12\x18\n" +
	"\aSummary\x18\x04 \x01(\tR\aSummary\"\x88\x02\n" +
	"\tAgentInfo\x12\x18\n" +
	"\aEnabled\x18\x01 \x01(\bR\aEnabled\x12\x1e\n" +
	"\n" +
	"Configured\x18\x02 \x01(\bR\n" +
	"Configured\x12\x1a\n" +
	"\bProvider\x18\x03 \x01(\tR\bProvider\x12\x14\n" +
	"\x05Model\x18\x04 \x01(\tR\x05Model\x12'\n" +
	"\x05Tools\x18\x05 \x03(\v2\x11.ai.AgentToolInfoR\x05Tools\x12$\n" +
	"\rMaxInputChars\x18\x06 \x01(\x03R\rMaxInputChars\x12\x1a\n" +
	"\bMaxSteps\x18\a \x01(\x03R\bMaxSteps\x12$\n" +
	"\rMaxRunSeconds\x18\b \x01(\x03R\rMaxRunSeconds\"\x8b\x03\n" +
	"\bAgentRun\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12&\n" +
	"\x0eConversationId\x18\x02 \x01(\tR\x0eConversationId\x12\x1c\n" +
	"\tRequestId\x18\x03 \x01(\tR\tRequestId\x12\x16\n" +
	"\x06Status\x18\x04 \x01(\tR\x06Status\x12\x16\n" +
	"\x06Answer\x18\x05 \x01(\tR\x06Answer\x12\x14\n" +
	"\x05Error\x18\x06 \x01(\tR\x05Error\x12\x1a\n" +
	"\bProvider\x18\a \x01(\tR\bProvider\x12\x14\n" +
	"\x05Model\x18\b \x01(\tR\x05Model\x12 \n" +
	"\vInputTokens\x18\t \x01(\x03R\vInputTokens\x12\"\n" +
	"\fOutputTokens\x18\n" +
	" \x01(\x03R\fOutputTokens\x12\x1c\n" +
	"\tCreatedAt\x18\v \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\f \x01(\tR\tUpdatedAt\x12/\n" +
	"\tToolCalls\x18\r \x03(\v2\x11.ai.AgentToolCallR\tToolCalls\"u\n" +
	"\x11AgentConversation\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x1c\n" +
	"\tCreatedAt\x18\x03 \x01(\tR\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\x04 \x01(\tR\tUpdatedAt\"\xa8\x01\n" +
	"\fAgentMessage\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12&\n" +
	"\x0eConversationId\x18\x02 \x01(\tR\x0eConversationId\x12\x14\n" +
	"\x05RunId\x18\x03 \x01(\tR\x05RunId\x12\x12\n" +
	"\x04Role\x18\x04 \x01(\tR\x04Role\x12\x18\n" +
	"\aContent\x18\x05 \x01(\tR\aContent\x12\x1c\n" +
	"\tCreatedAt\x18\x06 \x01(\tR\tCreatedAt\"<\n" +
	"\x10AgentInfoRequest\x12(\n" +
	"\x05Actor\x18\x01 \x01(\v2\x12.ai.SessionRequestR\x05Actor\"\xa1\x01\n" +
	"\x15CreateAgentRunRequest\x12(\n" +
	"\x05Actor\x18\x01 \x01(\v2\x12.ai.SessionRequestR\x05Actor\x12&\n" +
	"\x0eConversationId\x18\x02 \x01(\tR\x0eConversationId\x12\x1c\n" +
	"\tRequestId\x18\x03 \x01(\tR\tRequestId\x12\x18\n" +
	"\aMessage\x18\x04 \x01(\tR\aMessage\"J\n" +
	"\x0eAgentIDRequest\x12(\n" +
	"\x05Actor\x18\x01 \x01(\v2\x12.ai.SessionRequestR\x05Actor\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\"p\n" +
	"\x10AgentPageRequest\x12(\n" +
	"\x05Actor\x18\x01 \x01(\v2\x12.ai.SessionRequestR\x05Actor\x12\x16\n" +
	"\x06PageNo\x18\x02 \x01(\x03R\x06PageNo\x12\x1a\n" +
	"\bPageSize\x18\x03 \x01(\x03R\bPageSize\"\x87\x01\n" +
	"\x17AgentMessageListRequest\x12(\n" +
	"\x05Actor\x18\x01 \x01(\v2\x12.ai.SessionRequestR\x05Actor\x12\x0e\n" +
	"\x02ID\x18\x02 \x01(\tR\x02ID\x12\x16\n" +
	"\x06PageNo\x18\x03 \x01(\x03R\x06PageNo\x12\x1a\n" +
	"\bPageSize\x18\x04 \x01(\x03R\bPageSize\"b\n" +
	"\x1dAgentConversationListResponse\x12+\n" +
	"\x05Items\x18\x01 \x03(\v2\x15.ai.AgentConversationR\x05Items\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x03R\x05Total\"X\n" +
	"\x18AgentMessageListResponse\x12&\n" +
	"\x05Items\x18\x01 \x03(\v2\x10.ai.AgentMessageR\x05Items\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x03R\x05Total2\xff\x02\n" +
	"\x05Agent\x123\n" +
	"\fGetAgentInfo\x12\x14.ai.AgentInfoRequest\x1a\r.ai.AgentInfo\x129\n" +
	"\x0eCreateAgentRun\x12\x19.ai.CreateAgentRunRequest\x1a\f.ai.AgentRun\x12/\n" +
	"\vGetAgentRun\x12\x12.ai.AgentIDRequest\x1a\f.ai.AgentRun\x122\n" +
	"\x0eCancelAgentRun\x12\x12.ai.AgentIDRequest\x1a\f.ai.AgentRun\x12Q\n" +
	"\x16ListAgentConversations\x12\x14.ai.AgentPageRequest\x1a!.ai.AgentConversationListResponse\x12N\n" +
	"\x11ListAgentMessages\x12\x1b.ai.AgentMessageListRequest\x1a\x1c.ai.AgentMessageListResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_application_ai_rpc_desc_ai_proto_rawDescOnce sync.Once
	file_application_ai_rpc_desc_ai_proto_rawDescData []byte
)

func file_application_ai_rpc_desc_ai_proto_rawDescGZIP() []byte {
	file_application_ai_rpc_desc_ai_proto_rawDescOnce.Do(func() {
		file_application_ai_rpc_desc_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_ai_rpc_desc_ai_proto_rawDesc), len(file_application_ai_rpc_desc_ai_proto_rawDesc)))
	})
	return file_application_ai_rpc_desc_ai_proto_rawDescData
}

var file_application_ai_rpc_desc_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_application_ai_rpc_desc_ai_proto_goTypes = []any{
	(*SessionRequest)(nil),                // 0: ai.SessionRequest
	(*AgentToolInfo)(nil),                 // 1: ai.AgentToolInfo
	(*AgentToolCall)(nil),                 // 2: ai.AgentToolCall
	(*AgentInfo)(nil),                     // 3: ai.AgentInfo
	(*AgentRun)(nil),                      // 4: ai.AgentRun
	(*AgentConversation)(nil),             // 5: ai.AgentConversation
	(*AgentMessage)(nil),                  // 6: ai.AgentMessage
	(*AgentInfoRequest)(nil),              // 7: ai.AgentInfoRequest
	(*CreateAgentRunRequest)(nil),         // 8: ai.CreateAgentRunRequest
	(*AgentIDRequest)(nil),                // 9: ai.AgentIDRequest
	(*AgentPageRequest)(nil),              // 10: ai.AgentPageRequest
	(*AgentMessageListRequest)(nil),       // 11: ai.AgentMessageListRequest
	(*AgentConversationListResponse)(nil), // 12: ai.AgentConversationListResponse
	(*AgentMessageListResponse)(nil),      // 13: ai.AgentMessageListResponse
}
var file_application_ai_rpc_desc_ai_proto_depIdxs = []int32{
	1,  // 0: ai.AgentInfo.Tools:type_name -> ai.AgentToolInfo
	2,  // 1: ai.AgentRun.ToolCalls:type_name -> ai.AgentToolCall
	0,  // 2: ai.AgentInfoRequest.Actor:type_name -> ai.SessionRequest
	0,  // 3: ai.CreateAgentRunRequest.Actor:type_name -> ai.SessionRequest
	0,  // 4: ai.AgentIDRequest.Actor:type_name -> ai.SessionRequest
	0,  // 5: ai.AgentPageRequest.Actor:type_name -> ai.SessionRequest
	0,  // 6: ai.AgentMessageListRequest.Actor:type_name -> ai.SessionRequest
	5,  // 7: ai.AgentConversationListResponse.Items:type_name -> ai.AgentConversation
	6,  // 8: ai.AgentMessageListResponse.Items:type_name -> ai.AgentMessage
	7,  // 9: ai.Agent.GetAgentInfo:input_type -> ai.AgentInfoRequest
	8,  // 10: ai.Agent.CreateAgentRun:input_type -> ai.CreateAgentRunRequest
	9,  // 11: ai.Agent.GetAgentRun:input_type -> ai.AgentIDRequest
	9,  // 12: ai.Agent.CancelAgentRun:input_type -> ai.AgentIDRequest
	10, // 13: ai.Agent.ListAgentConversations:input_type -> ai.AgentPageRequest
	11, // 14: ai.Agent.ListAgentMessages:input_type -> ai.AgentMessageListRequest
	3,  // 15: ai.Agent.GetAgentInfo:output_type -> ai.AgentInfo
	4,  // 16: ai.Agent.CreateAgentRun:output_type -> ai.AgentRun
	4,  // 17: ai.Agent.GetAgentRun:output_type -> ai.AgentRun
	4,  // 18: ai.Agent.CancelAgentRun:output_type -> ai.AgentRun
	12, // 19: ai.Agent.ListAgentConversations:output_type -> ai.AgentConversationListResponse
	13, // 20: ai.Agent.ListAgentMessages:output_type -> ai.AgentMessageListResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_application_ai_rpc_desc_ai_proto_init() }
func file_application_ai_rpc_desc_ai_proto_init() {
	if File_application_ai_rpc_desc_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_ai_rpc_desc_ai_proto_rawDesc), len(file_application_ai_rpc_desc_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_application_ai_rpc_desc_ai_proto_goTypes,
		DependencyIndexes: file_application_ai_rpc_desc_ai_proto_depIdxs,
		MessageInfos:      file_application_ai_rpc_desc_ai_proto_msgTypes,
	}.Build()
	File_application_ai_rpc_desc_ai_proto = out.File
	file_application_ai_rpc_desc_ai_proto_goTypes = nil
	file_application_ai_rpc_desc_ai_proto_depIdxs = nil
}
