// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.1
// source: application/ai/rpc/desc/ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_GetAgentInfo_FullMethodName           = "/ai.Agent/GetAgentInfo"
	Agent_CreateAgentRun_FullMethodName         = "/ai.Agent/CreateAgentRun"
	Agent_GetAgentRun_FullMethodName            = "/ai.Agent/GetAgentRun"
	Agent_CancelAgentRun_FullMethodName         = "/ai.Agent/CancelAgentRun"
	Agent_ListAgentConversations_FullMethodName = "/ai.Agent/ListAgentConversations"
	Agent_ListAgentMessages_FullMethodName      = "/ai.Agent/ListAgentMessages"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	GetAgentInfo(ctx context.Context, in *AgentInfoRequest, opts ...grpc.CallOption) (*AgentInfo, error)
	CreateAgentRun(ctx context.Context, in *CreateAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error)
	GetAgentRun(ctx context.Context, in *AgentIDRequest, opts ...grpc.CallOption) (*AgentRun, error)
	CancelAgentRun(ctx context.Context, in *AgentIDRequest, opts ...grpc.CallOption) (*AgentRun, error)
	ListAgentConversations(ctx context.Context, in *AgentPageRequest, opts ...grpc.CallOption) (*AgentConversationListResponse, error)
	ListAgentMessages(ctx context.Context, in *AgentMessageListRequest, opts ...grpc.CallOption) (*AgentMessageListResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) GetAgentInfo(ctx context.Context, in *AgentInfoRequest, opts ...grpc.CallOption) (*AgentInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInfo)
	err := c.cc.Invoke(ctx, Agent_GetAgentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CreateAgentRun(ctx context.Context, in *CreateAgentRunRequest, opts ...grpc.CallOption) (*AgentRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRun)
	err := c.cc.Invoke(ctx, Agent_CreateAgentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetAgentRun(ctx context.Context, in *AgentIDRequest, opts ...grpc.CallOption) (*AgentRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRun)
	err := c.cc.Invoke(ctx, Agent_GetAgentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CancelAgentRun(ctx context.Context, in *AgentIDRequest, opts ...grpc.CallOption) (*AgentRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRun)
	err := c.cc.Invoke(ctx, Agent_CancelAgentRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListAgentConversations(ctx context.Context, in *AgentPageRequest, opts ...grpc.CallOption) (*AgentConversationListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConversationListResponse)
	err := c.cc.Invoke(ctx, Agent_ListAgentConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListAgentMessages(ctx context.Context, in *AgentMessageListRequest, opts ...grpc.CallOption) (*AgentMessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentMessageListResponse)
	err := c.cc.Invoke(ctx, Agent_ListAgentMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
type AgentServer interface {
	GetAgentInfo(context.Context, *AgentInfoRequest) (*AgentInfo, error)
	CreateAgentRun(context.Context, *CreateAgentRunRequest) (*AgentRun, error)
	GetAgentRun(context.Context, *AgentIDRequest) (*AgentRun, error)
	CancelAgentRun(context.Context, *AgentIDRequest) (*AgentRun, error)
	ListAgentConversations(context.Context, *AgentPageRequest) (*AgentConversationListResponse, error)
	ListAgentMessages(context.Context, *AgentMessageListRequest) (*AgentMessageListResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) GetAgentInfo(context.Context, *AgentInfoRequest) (*AgentInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentInfo not implemented")
}
func (UnimplementedAgentServer) CreateAgentRun(context.Context, *CreateAgentRunRequest) (*AgentRun, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgentRun not implemented")
}
func (UnimplementedAgentServer) GetAgentRun(context.Context, *AgentIDRequest) (*AgentRun, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentRun not implemented")
}
func (UnimplementedAgentServer) CancelAgentRun(context.Context, *AgentIDRequest) (*AgentRun, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAgentRun not implemented")
}
func (UnimplementedAgentServer) ListAgentConversations(context.Context, *AgentPageRequest) (*AgentConversationListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentConversations not implemented")
}
func (UnimplementedAgentServer) ListAgentMessages(context.Context, *AgentMessageListRequest) (*AgentMessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentMessages not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_GetAgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetAgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetAgentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetAgentInfo(ctx, req.(*AgentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CreateAgentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateAgentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_CreateAgentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateAgentRun(ctx, req.(*CreateAgentRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetAgentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetAgentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetAgentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetAgentRun(ctx, req.(*AgentIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CancelAgentRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CancelAgentRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_CancelAgentRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CancelAgentRun(ctx, req.(*AgentIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListAgentConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListAgentConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListAgentConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListAgentConversations(ctx, req.(*AgentPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListAgentMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListAgentMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListAgentMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListAgentMessages(ctx, req.(*AgentMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentInfo",
			Handler:    _Agent_GetAgentInfo_Handler,
		},
		{
			MethodName: "CreateAgentRun",
			Handler:    _Agent_CreateAgentRun_Handler,
		},
		{
			MethodName: "GetAgentRun",
			Handler:    _Agent_GetAgentRun_Handler,
		},
		{
			MethodName: "CancelAgentRun",
			Handler:    _Agent_CancelAgentRun_Handler,
		},
		{
			MethodName: "ListAgentConversations",
			Handler:    _Agent_ListAgentConversations_Handler,
		},
		{
			MethodName: "ListAgentMessages",
			Handler:    _Agent_ListAgentMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application/ai/rpc/desc/ai.proto",
}
