// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"
	"time"

	aiagent "go-zero-admin/application/applet/api/internal/handler/aiagent"
	api "go-zero-admin/application/applet/api/internal/handler/api"
	audit "go-zero-admin/application/applet/api/internal/handler/audit"
	authority "go-zero-admin/application/applet/api/internal/handler/authority"
	base "go-zero-admin/application/applet/api/internal/handler/base"
	casbin "go-zero-admin/application/applet/api/internal/handler/casbin"
	devicesession "go-zero-admin/application/applet/api/internal/handler/devicesession"
	dictionary "go-zero-admin/application/applet/api/internal/handler/dictionary"
	files "go-zero-admin/application/applet/api/internal/handler/files"
	menu "go-zero-admin/application/applet/api/internal/handler/menu"
	organization "go-zero-admin/application/applet/api/internal/handler/organization"
	permission "go-zero-admin/application/applet/api/internal/handler/permission"
	session "go-zero-admin/application/applet/api/internal/handler/session"
	user "go-zero-admin/application/applet/api/internal/handler/user"
	usernocasbin "go-zero-admin/application/applet/api/internal/handler/usernocasbin"
	"go-zero-admin/application/applet/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/conversations",
					Handler: aiagent.ListAgentConversationsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/conversations/:id/messages",
					Handler: aiagent.ListAgentMessagesHandler(serverCtx),
				},
				{
					// 查询AI开关、模型名称和当前用户可用的只读工具
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: aiagent.GetAgentInfoHandler(serverCtx),
				},
				{
					// 提交有界异步Agent任务，同一requestId幂等
					Method:  http.MethodPost,
					Path:    "/runs",
					Handler: aiagent.CreateAgentRunHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/runs/:id",
					Handler: aiagent.GetAgentRunHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/runs/:id/cancel",
					Handler: aiagent.CancelAgentRunHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/ai"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 创建/增加 api列表
					Method:  http.MethodPost,
					Path:    "/createApi",
					Handler: api.CreateApiHandler(serverCtx),
				},
				{
					// 删除 api列表
					Method:  http.MethodDelete,
					Path:    "/deleteApi",
					Handler: api.DeleteApiHandler(serverCtx),
				},
				{
					// 删除多条api
					Method:  http.MethodDelete,
					Path:    "/deleteApisByIds",
					Handler: api.DeleteApisByIdsHandler(serverCtx),
				},
				{
					// 获取 所有api
					Method:  http.MethodGet,
					Path:    "/getAllApiList",
					Handler: api.GetAllApiListHandler(serverCtx),
				},
				{
					// 获取api列表
					Method:  http.MethodGet,
					Path:    "/getApiList",
					Handler: api.GetApiListHandler(serverCtx),
				},
				{
					// 更新api
					Method:  http.MethodPut,
					Path:    "/updateApi",
					Handler: api.UpdateApiHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 按预览版本同步选中API，仅新增资源或更新分组描述，保留授权
					Method:  http.MethodPost,
					Path:    "/applySync",
					Handler: api.ApplyApiSyncHandler(serverCtx),
				},
				{
					// 预览Swagger与API资源差异，失效资源仅提示
					Method:  http.MethodGet,
					Path:    "/previewSync",
					Handler: api.PreviewApiSyncHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/api"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 分页查询操作审计与登录日志，时间使用RFC3339格式
					Method:  http.MethodGet,
					Path:    "/getAuditLogList",
					Handler: audit.GetAuditLogListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/audit"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 增加角色和base_menu关联关系
					Method:  http.MethodPost,
					Path:    "/addAuthorityMenu",
					Handler: authority.AddAuthorityMenuHandler(serverCtx),
				},
				{
					// 创建角色
					Method:  http.MethodPost,
					Path:    "/createAuthority",
					Handler: authority.CreateAuthorityHandler(serverCtx),
				},
				{
					// 删除角色
					Method:  http.MethodDelete,
					Path:    "/deleteAuthority",
					Handler: authority.DeleteAuthorityHandler(serverCtx),
				},
				{
					// 获取角色列表
					Method:  http.MethodGet,
					Path:    "/getAuthorityList",
					Handler: authority.GetAuthorityListHandler(serverCtx),
				},
				{
					// 更新角色 -- 设为首页
					Method:  http.MethodPut,
					Path:    "/updateAuthority",
					Handler: authority.UpdateAuthorityHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/authority"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 上传图片
					Method:  http.MethodPost,
					Path:    "/uploadFileImg",
					Handler: base.UploadFileImgHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/base"),
		rest.WithTimeout(30000*time.Millisecond),
		rest.WithMaxBytes(11534336),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 邮箱发送验证码 - 暂时用于注册账号
					Method:  http.MethodPost,
					Path:    "/sendEmailCode",
					Handler: base.SendEmailCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/base"),
		rest.WithTimeout(30000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 根据角色id获取对应的casbin数据
					Method:  http.MethodGet,
					Path:    "/getPathByAuthorityId",
					Handler: casbin.GetPathByAuthorityIdHandler(serverCtx),
				},
				{
					// 更新一个角色的对应的casbin数据
					Method:  http.MethodPut,
					Path:    "/updateCasbinData",
					Handler: casbin.UpdateCasbinDataHandler(serverCtx),
				},
				{
					// 更新一个角色的对应的casbin数据 用api的ids 查数据
					Method:  http.MethodPut,
					Path:    "/updateCasbinDataByApiIds",
					Handler: casbin.UpdateCasbinDataByApiIdsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/casbin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Session},
			[]rest.Route{
				{
					// 撤销自己的一个设备会话
					Method:  http.MethodDelete,
					Path:    "/device",
					Handler: devicesession.RevokeMyDeviceSessionHandler(serverCtx),
				},
				{
					// 查询自己的有效设备会话
					Method:  http.MethodGet,
					Path:    "/devices",
					Handler: devicesession.GetMyDeviceSessionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/session"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 管理员撤销一个设备会话
					Method:  http.MethodDelete,
					Path:    "/device",
					Handler: devicesession.RevokeDeviceSessionHandler(serverCtx),
				},
				{
					// 管理员查询有效设备会话
					Method:  http.MethodGet,
					Path:    "/devices",
					Handler: devicesession.GetDeviceSessionsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/session/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 新建SysDictionary
					Method:  http.MethodPost,
					Path:    "/createSysDictionary",
					Handler: dictionary.CreateSysDictionaryHandler(serverCtx),
				},
				{
					// 创建SysDictionaryInfo
					Method:  http.MethodPost,
					Path:    "/createSysDictionaryInfo",
					Handler: dictionary.CreateSysDictionaryInfoHandler(serverCtx),
				},
				{
					// 删除SysDictionary
					Method:  http.MethodDelete,
					Path:    "/deleteSysDictionary",
					Handler: dictionary.DeleteSysDictionaryHandler(serverCtx),
				},
				{
					// 删除SysDictionaryInfo
					Method:  http.MethodDelete,
					Path:    "/deleteSysDictionaryInfo",
					Handler: dictionary.DeleteSysDictionaryInfoHandler(serverCtx),
				},
				{
					// 根据ID或者type获取SysDictionary
					Method:  http.MethodGet,
					Path:    "/getSysDictionaryDetails",
					Handler: dictionary.GetSysDictionaryDetailsHandler(serverCtx),
				},
				{
					// 获取SysDictionaryInfo列表
					Method:  http.MethodGet,
					Path:    "/getSysDictionaryInfoList",
					Handler: dictionary.GetSysDictionaryInfoListHandler(serverCtx),
				},
				{
					// 根据id获取SysDictionaryInfo详情
					Method:  http.MethodGet,
					Path:    "/getSysDictionaryInfoListDetailsById",
					Handler: dictionary.GetSysDictionaryInfoListDetailsByIdHandler(serverCtx),
				},
				{
					// 获取SysDictionary列表
					Method:  http.MethodGet,
					Path:    "/getSysDictionaryList",
					Handler: dictionary.GetSysDictionaryListHandler(serverCtx),
				},
				{
					// 更新SysDictionary
					Method:  http.MethodPut,
					Path:    "/updateSysDictionary",
					Handler: dictionary.UpdateSysDictionaryHandler(serverCtx),
				},
				{
					// 更新SysDictionaryInfo
					Method:  http.MethodPut,
					Path:    "/updateSysDictionaryInfo",
					Handler: dictionary.UpdateSysDictionaryInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/dictionary"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 按数据范围分页查询文件
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: files.GetFileListHandler(serverCtx),
				},
				{
					// 登记文件业务引用
					Method:  http.MethodPost,
					Path:    "/reference",
					Handler: files.AddFileReferenceHandler(serverCtx),
				},
				{
					// 移除文件业务引用
					Method:  http.MethodDelete,
					Path:    "/reference",
					Handler: files.RemoveFileReferenceHandler(serverCtx),
				},
				{
					// 删除无引用文件，失败可重试
					Method:  http.MethodDelete,
					Path:    "/resource",
					Handler: files.DeleteFileHandler(serverCtx),
				},
				{
					// 获取受控文件访问地址
					Method:  http.MethodGet,
					Path:    "/url",
					Handler: files.GetFileURLHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/files"),
		rest.WithTimeout(30000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 新增 base_menu
					Method:  http.MethodPost,
					Path:    "/addBaseMenu",
					Handler: menu.AddBaseMenuHandler(serverCtx),
				},
				{
					// 删除系统菜单
					Method:  http.MethodDelete,
					Path:    "/deleteBaseMenu",
					Handler: menu.DeleteBaseMenuHandler(serverCtx),
				},
				{
					// 读取指定角色按钮授权
					Method:  http.MethodGet,
					Path:    "/getAuthorityButtons",
					Handler: menu.GetAuthorityButtonsHandler(serverCtx),
				},
				{
					// 根据id获取菜单
					Method:  http.MethodGet,
					Path:    "/getBaseMenuById",
					Handler: menu.GetBaseMenuByIdHandler(serverCtx),
				},
				{
					// 获取用户动态路由树  -- 用于角色管理的设置权限
					Method:  http.MethodGet,
					Path:    "/getBaseMenuTree",
					Handler: menu.GetBaseMenuTreeHandler(serverCtx),
				},
				{
					// 获取菜单
					Method:  http.MethodGet,
					Path:    "/getMenu",
					Handler: menu.GetMenuHandler(serverCtx),
				},
				{
					// 获取指定角色menu  -- 用于角色管理的设置权限
					Method:  http.MethodGet,
					Path:    "/getMenuAuthority",
					Handler: menu.GetMenuAuthorityHandler(serverCtx),
				},
				{
					// 获取完整base_menu树，分页参数仅兼容保留，不参与分页
					Method:  http.MethodGet,
					Path:    "/getMenuList",
					Handler: menu.GetMenuListHandler(serverCtx),
				},
				{
					// 保存指定角色按钮授权
					Method:  http.MethodPut,
					Path:    "/updateAuthorityButtons",
					Handler: menu.UpdateAuthorityButtonsHandler(serverCtx),
				},
				{
					// 更新系统菜单
					Method:  http.MethodPut,
					Path:    "/updateBaseMenu",
					Handler: menu.UpdateBaseMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/previewMove",
					Handler: menu.PreviewMenuMoveHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 读取角色数据范围
					Method:  http.MethodGet,
					Path:    "/dataScope",
					Handler: organization.GetRoleDataScopeHandler(serverCtx),
				},
				{
					// 设置角色数据范围
					Method:  http.MethodPut,
					Path:    "/dataScope",
					Handler: organization.UpdateRoleDataScopeHandler(serverCtx),
				},
				{
					// 查询部门树
					Method:  http.MethodGet,
					Path:    "/departments",
					Handler: organization.GetDepartmentTreeHandler(serverCtx),
				},
				{
					// 创建部门
					Method:  http.MethodPost,
					Path:    "/departments",
					Handler: organization.CreateDepartmentHandler(serverCtx),
				},
				{
					// 更新部门
					Method:  http.MethodPut,
					Path:    "/departments",
					Handler: organization.UpdateDepartmentHandler(serverCtx),
				},
				{
					// 删除未被使用的部门
					Method:  http.MethodDelete,
					Path:    "/departments",
					Handler: organization.DeleteDepartmentHandler(serverCtx),
				},
				{
					// 读取人员部门岗位归属
					Method:  http.MethodGet,
					Path:    "/membership",
					Handler: organization.GetMembershipHandler(serverCtx),
				},
				{
					// 设置人员部门岗位归属
					Method:  http.MethodPut,
					Path:    "/membership",
					Handler: organization.UpdateMembershipHandler(serverCtx),
				},
				{
					// 查询岗位列表
					Method:  http.MethodGet,
					Path:    "/positions",
					Handler: organization.GetPositionListHandler(serverCtx),
				},
				{
					// 创建岗位
					Method:  http.MethodPost,
					Path:    "/positions",
					Handler: organization.CreatePositionHandler(serverCtx),
				},
				{
					// 更新岗位
					Method:  http.MethodPut,
					Path:    "/positions",
					Handler: organization.UpdatePositionHandler(serverCtx),
				},
				{
					// 删除未被使用的岗位
					Method:  http.MethodDelete,
					Path:    "/positions",
					Handler: organization.DeletePositionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/organization"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/edit",
					Handler: permission.GetPermissionEditHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/history",
					Handler: permission.GetPermissionHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/rollback/apply",
					Handler: permission.ApplyPermissionRollbackHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/rollback/preview",
					Handler: permission.PreviewPermissionRollbackHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/permissions"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Session},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/snapshot",
					Handler: permission.GetPermissionSnapshotHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/permissions"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Session},
			[]rest.Route{
				{
					// 修改自己的密码并撤销全部会话
					Method:  http.MethodPut,
					Path:    "/changePassword",
					Handler: session.ChangePasswordHandler(serverCtx),
				},
				{
					// 退出登录并撤销该用户全部会话
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: session.LogoutHandler(serverCtx),
				},
				{
					// 获取当前登录用户
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: session.MeHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					// 删除用户
					Method:  http.MethodDelete,
					Path:    "/deleteUser",
					Handler: user.DeleteUserHandler(serverCtx),
				},
				{
					// 分页获取用户列表
					Method:  http.MethodGet,
					Path:    "/getUserList",
					Handler: user.GetUserListHandler(serverCtx),
				},
				{
					// 新增（注册）用户 - 管理员
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: user.RegisterHandler(serverCtx),
				},
				{
					// 重置用户密码，使用服务端配置的默认密码
					Method:  http.MethodPut,
					Path:    "/resetUserPassword",
					Handler: user.ResetUserPasswordHandler(serverCtx),
				},
				{
					// 修改用户信息
					Method:  http.MethodPut,
					Path:    "/updateUserInfo",
					Handler: user.UpdateUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authority},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/resources",
					Handler: user.GetUserResourcePreviewHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/resources/transfer",
					Handler: user.TransferUserResourcesHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/v1/sys/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: usernocasbin.LoginHandler(serverCtx),
			},
			{
				// 生成验证码
				Method:  http.MethodGet,
				Path:    "/randomImage",
				Handler: usernocasbin.RandomImageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/sys"),
	)
}
