// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package server

import (
	"context"

	"go-zero-admin/application/applet/rpc/internal/logic/audit"
	"go-zero-admin/application/applet/rpc/internal/svc"
	"go-zero-admin/application/applet/rpc/pb"
)

type AuditServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuditServer
}

func NewAuditServer(svcCtx *svc.ServiceContext) *AuditServer {
	return &AuditServer{
		svcCtx: svcCtx,
	}
}

func (s *AuditServer) RecordAudit(ctx context.Context, in *pb.RecordAuditRequest) (*pb.NoDataResponse, error) {
	l := auditlogic.NewRecordAuditLogic(ctx, s.svcCtx)
	return l.RecordAudit(in)
}

func (s *AuditServer) GetAuditLogList(ctx context.Context, in *pb.GetAuditLogListRequest) (*pb.GetAuditLogListResponse, error) {
	l := auditlogic.NewGetAuditLogListLogic(ctx, s.svcCtx)
	return l.GetAuditLogList(in)
}
