// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package server

import (
	"context"

	"go-zero-admin/application/applet/rpc/internal/logic/agenttools"
	"go-zero-admin/application/applet/rpc/internal/svc"
	"go-zero-admin/application/applet/rpc/pb"
)

type AgentToolsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAgentToolsServer
}

func NewAgentToolsServer(svcCtx *svc.ServiceContext) *AgentToolsServer {
	return &AgentToolsServer{
		svcCtx: svcCtx,
	}
}

func (s *AgentToolsServer) QueryAgentAudit(ctx context.Context, in *pb.AgentToolRequest) (*pb.AgentToolResult, error) {
	l := agenttoolslogic.NewQueryAgentAuditLogic(ctx, s.svcCtx)
	return l.QueryAgentAudit(in)
}

func (s *AgentToolsServer) GetAgentFileStatus(ctx context.Context, in *pb.AgentToolRequest) (*pb.AgentToolResult, error) {
	l := agenttoolslogic.NewGetAgentFileStatusLogic(ctx, s.svcCtx)
	return l.GetAgentFileStatus(in)
}

func (s *AgentToolsServer) ListAgentDevices(ctx context.Context, in *pb.AgentToolRequest) (*pb.AgentToolResult, error) {
	l := agenttoolslogic.NewListAgentDevicesLogic(ctx, s.svcCtx)
	return l.ListAgentDevices(in)
}
