// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: ai.proto

package server

import (
	"context"

	"go-zero-admin/application/ai/rpc/internal/logic/agent"
	"go-zero-admin/application/ai/rpc/internal/svc"
	"go-zero-admin/application/ai/rpc/pb"
)

type AgentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAgentServer
}

func NewAgentServer(svcCtx *svc.ServiceContext) *AgentServer {
	return &AgentServer{
		svcCtx: svcCtx,
	}
}

func (s *AgentServer) GetAgentInfo(ctx context.Context, in *pb.AgentInfoRequest) (*pb.AgentInfo, error) {
	l := agentlogic.NewGetAgentInfoLogic(ctx, s.svcCtx)
	return l.GetAgentInfo(in)
}

func (s *AgentServer) CreateAgentRun(ctx context.Context, in *pb.CreateAgentRunRequest) (*pb.AgentRun, error) {
	l := agentlogic.NewCreateAgentRunLogic(ctx, s.svcCtx)
	return l.CreateAgentRun(in)
}

func (s *AgentServer) GetAgentRun(ctx context.Context, in *pb.AgentIDRequest) (*pb.AgentRun, error) {
	l := agentlogic.NewGetAgentRunLogic(ctx, s.svcCtx)
	return l.GetAgentRun(in)
}

func (s *AgentServer) CancelAgentRun(ctx context.Context, in *pb.AgentIDRequest) (*pb.AgentRun, error) {
	l := agentlogic.NewCancelAgentRunLogic(ctx, s.svcCtx)
	return l.CancelAgentRun(in)
}

func (s *AgentServer) ListAgentConversations(ctx context.Context, in *pb.AgentPageRequest) (*pb.AgentConversationListResponse, error) {
	l := agentlogic.NewListAgentConversationsLogic(ctx, s.svcCtx)
	return l.ListAgentConversations(in)
}

func (s *AgentServer) ListAgentMessages(ctx context.Context, in *pb.AgentMessageListRequest) (*pb.AgentMessageListResponse, error) {
	l := agentlogic.NewListAgentMessagesLogic(ctx, s.svcCtx)
	return l.ListAgentMessages(in)
}
