// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package casbin

import (
	"context"

	"go-zero-admin/application/applet/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CasbinInfo                       = pb.CasbinInfo
	EnforceRequest                   = pb.EnforceRequest
	EnforceResponse                  = pb.EnforceResponse
	GetPathByAuthorityIdRequest      = pb.GetPathByAuthorityIdRequest
	GetPathByAuthorityIdResponse     = pb.GetPathByAuthorityIdResponse
	NoDataResponse                   = pb.NoDataResponse
	SysApi                           = pb.SysApi
	UpdateCasbinDataByApiIdsRequest  = pb.UpdateCasbinDataByApiIdsRequest
	UpdateCasbinDataByApiIdsResponse = pb.UpdateCasbinDataByApiIdsResponse
	UpdateCasbinDataRequest          = pb.UpdateCasbinDataRequest

	Casbin interface {
		// 根据角色id获取对应的casbin数据
		GetPathByAuthorityId(ctx context.Context, in *GetPathByAuthorityIdRequest, opts ...grpc.CallOption) (*GetPathByAuthorityIdResponse, error)
		// 更新一个角色的对应的casbin数据
		UpdateCasbinData(ctx context.Context, in *UpdateCasbinDataRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		// 更新一个角色的对应的casbin数据 用api的ids 查数据
		UpdateCasbinDataByApiIds(ctx context.Context, in *UpdateCasbinDataByApiIdsRequest, opts ...grpc.CallOption) (*UpdateCasbinDataByApiIdsResponse, error)
		// casbin 鉴权 供api网关/中间件调用
		Enforce(ctx context.Context, in *EnforceRequest, opts ...grpc.CallOption) (*EnforceResponse, error)
	}

	defaultCasbin struct {
		cli zrpc.Client
	}
)

func NewCasbin(cli zrpc.Client) Casbin {
	return &defaultCasbin{
		cli: cli,
	}
}

// 根据角色id获取对应的casbin数据
func (m *defaultCasbin) GetPathByAuthorityId(ctx context.Context, in *GetPathByAuthorityIdRequest, opts ...grpc.CallOption) (*GetPathByAuthorityIdResponse, error) {
	client := pb.NewCasbinClient(m.cli.Conn())
	return client.GetPathByAuthorityId(ctx, in, opts...)
}

// 更新一个角色的对应的casbin数据
func (m *defaultCasbin) UpdateCasbinData(ctx context.Context, in *UpdateCasbinDataRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewCasbinClient(m.cli.Conn())
	return client.UpdateCasbinData(ctx, in, opts...)
}

// 更新一个角色的对应的casbin数据 用api的ids 查数据
func (m *defaultCasbin) UpdateCasbinDataByApiIds(ctx context.Context, in *UpdateCasbinDataByApiIdsRequest, opts ...grpc.CallOption) (*UpdateCasbinDataByApiIdsResponse, error) {
	client := pb.NewCasbinClient(m.cli.Conn())
	return client.UpdateCasbinDataByApiIds(ctx, in, opts...)
}

// casbin 鉴权 供api网关/中间件调用
func (m *defaultCasbin) Enforce(ctx context.Context, in *EnforceRequest, opts ...grpc.CallOption) (*EnforceResponse, error) {
	client := pb.NewCasbinClient(m.cli.Conn())
	return client.Enforce(ctx, in, opts...)
}
