// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package organization

import (
	"context"

	"go-zero-admin/application/applet/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Department              = pb.Department
	DepartmentListResponse  = pb.DepartmentListResponse
	DepartmentRequest       = pb.DepartmentRequest
	GetRoleDataScopeRequest = pb.GetRoleDataScopeRequest
	MembershipRequest       = pb.MembershipRequest
	MembershipResponse      = pb.MembershipResponse
	NoDataResponse          = pb.NoDataResponse
	OrganizationIDRequest   = pb.OrganizationIDRequest
	OrganizationListRequest = pb.OrganizationListRequest
	Position                = pb.Position
	PositionListResponse    = pb.PositionListResponse
	PositionRequest         = pb.PositionRequest
	RoleDataScope           = pb.RoleDataScope
	RoleDataScopeRequest    = pb.RoleDataScopeRequest
	RoleDataScopeResponse   = pb.RoleDataScopeResponse

	Organization interface {
		GetDepartmentTree(ctx context.Context, in *OrganizationListRequest, opts ...grpc.CallOption) (*DepartmentListResponse, error)
		CreateDepartment(ctx context.Context, in *DepartmentRequest, opts ...grpc.CallOption) (*Department, error)
		UpdateDepartment(ctx context.Context, in *DepartmentRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		DeleteDepartment(ctx context.Context, in *OrganizationIDRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		GetPositionList(ctx context.Context, in *OrganizationListRequest, opts ...grpc.CallOption) (*PositionListResponse, error)
		CreatePosition(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*Position, error)
		UpdatePosition(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		DeletePosition(ctx context.Context, in *OrganizationIDRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		GetMembership(ctx context.Context, in *OrganizationIDRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
		UpdateMembership(ctx context.Context, in *MembershipRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		GetRoleDataScope(ctx context.Context, in *GetRoleDataScopeRequest, opts ...grpc.CallOption) (*RoleDataScopeResponse, error)
		UpdateRoleDataScope(ctx context.Context, in *RoleDataScopeRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	}

	defaultOrganization struct {
		cli zrpc.Client
	}
)

func NewOrganization(cli zrpc.Client) Organization {
	return &defaultOrganization{
		cli: cli,
	}
}

func (m *defaultOrganization) GetDepartmentTree(ctx context.Context, in *OrganizationListRequest, opts ...grpc.CallOption) (*DepartmentListResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.GetDepartmentTree(ctx, in, opts...)
}

func (m *defaultOrganization) CreateDepartment(ctx context.Context, in *DepartmentRequest, opts ...grpc.CallOption) (*Department, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.CreateDepartment(ctx, in, opts...)
}

func (m *defaultOrganization) UpdateDepartment(ctx context.Context, in *DepartmentRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.UpdateDepartment(ctx, in, opts...)
}

func (m *defaultOrganization) DeleteDepartment(ctx context.Context, in *OrganizationIDRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.DeleteDepartment(ctx, in, opts...)
}

func (m *defaultOrganization) GetPositionList(ctx context.Context, in *OrganizationListRequest, opts ...grpc.CallOption) (*PositionListResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.GetPositionList(ctx, in, opts...)
}

func (m *defaultOrganization) CreatePosition(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*Position, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.CreatePosition(ctx, in, opts...)
}

func (m *defaultOrganization) UpdatePosition(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.UpdatePosition(ctx, in, opts...)
}

func (m *defaultOrganization) DeletePosition(ctx context.Context, in *OrganizationIDRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.DeletePosition(ctx, in, opts...)
}

func (m *defaultOrganization) GetMembership(ctx context.Context, in *OrganizationIDRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.GetMembership(ctx, in, opts...)
}

func (m *defaultOrganization) UpdateMembership(ctx context.Context, in *MembershipRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.UpdateMembership(ctx, in, opts...)
}

func (m *defaultOrganization) GetRoleDataScope(ctx context.Context, in *GetRoleDataScopeRequest, opts ...grpc.CallOption) (*RoleDataScopeResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.GetRoleDataScope(ctx, in, opts...)
}

func (m *defaultOrganization) UpdateRoleDataScope(ctx context.Context, in *RoleDataScopeRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewOrganizationClient(m.cli.Conn())
	return client.UpdateRoleDataScope(ctx, in, opts...)
}
