// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package audit

import (
	"context"

	"go-zero-admin/application/applet/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuditLog                = pb.AuditLog
	GetAuditLogListRequest  = pb.GetAuditLogListRequest
	GetAuditLogListResponse = pb.GetAuditLogListResponse
	NoDataResponse          = pb.NoDataResponse
	PageRequest             = pb.PageRequest
	RecordAuditRequest      = pb.RecordAuditRequest

	Audit interface {
		RecordAudit(ctx context.Context, in *RecordAuditRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
		GetAuditLogList(ctx context.Context, in *GetAuditLogListRequest, opts ...grpc.CallOption) (*GetAuditLogListResponse, error)
	}

	defaultAudit struct {
		cli zrpc.Client
	}
)

func NewAudit(cli zrpc.Client) Audit {
	return &defaultAudit{
		cli: cli,
	}
}

func (m *defaultAudit) RecordAudit(ctx context.Context, in *RecordAuditRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewAuditClient(m.cli.Conn())
	return client.RecordAudit(ctx, in, opts...)
}

func (m *defaultAudit) GetAuditLogList(ctx context.Context, in *GetAuditLogListRequest, opts ...grpc.CallOption) (*GetAuditLogListResponse, error) {
	client := pb.NewAuditClient(m.cli.Conn())
	return client.GetAuditLogList(ctx, in, opts...)
}
