// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AddAuthorityMenuRequest struct {
	ExpectedRevision string `json:"expectedRevision"`
	AuthorityId      int64  `json:"authorityId"`
	MenuIds          string `json:"menuIds"`
}

type AddBaseMenuRequest struct {
	SysBaseMenu
}

type AddBaseMenuResponse struct {
}

type AdminDeviceSessionListRequest struct {
	PageRequest
	UserId int64 `form:"userId,optional"`
}

type AgentConversation struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type AgentConversationListResponse struct {
	Items []AgentConversation `json:"items"`
	Total int64               `json:"total"`
}

type AgentIDRequest struct {
	ID string `path:"id"`
}

type AgentInfo struct {
	Enabled       bool            `json:"enabled"`
	Configured    bool            `json:"configured"`
	Provider      string          `json:"provider"`
	Model         string          `json:"model"`
	Tools         []AgentToolInfo `json:"tools"`
	MaxInputChars int64           `json:"maxInputChars"`
	MaxSteps      int64           `json:"maxSteps"`
	MaxRunSeconds int64           `json:"maxRunSeconds"`
}

type AgentMessage struct {
	ID             string `json:"id"`
	ConversationId string `json:"conversationId"`
	RunId          string `json:"runId"`
	Role           string `json:"role"`
	Content        string `json:"content"`
	CreatedAt      string `json:"createdAt"`
}

type AgentMessageListRequest struct {
	ID       string `path:"id"`
	PageNo   int64  `form:"pageNo,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
}

type AgentMessageListResponse struct {
	Items []AgentMessage `json:"items"`
	Total int64          `json:"total"`
}

type AgentPageRequest struct {
	PageNo   int64 `form:"pageNo,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
}

type AgentRun struct {
	ID             string          `json:"id"`
	ConversationId string          `json:"conversationId"`
	RequestId      string          `json:"requestId"`
	Status         string          `json:"status"`
	Answer         string          `json:"answer"`
	Error          string          `json:"error"`
	Provider       string          `json:"provider"`
	Model          string          `json:"model"`
	InputTokens    int64           `json:"inputTokens"`
	OutputTokens   int64           `json:"outputTokens"`
	CreatedAt      string          `json:"createdAt"`
	UpdatedAt      string          `json:"updatedAt"`
	ToolCalls      []AgentToolCall `json:"toolCalls"`
}

type AgentToolCall struct {
	Name    string `json:"name"`
	Status  string `json:"status"`
	Error   string `json:"error"`
	Summary string `json:"summary"`
}

type AgentToolInfo struct {
	Name        string `json:"name"`
	Label       string `json:"label"`
	Description string `json:"description"`
	Available   bool   `json:"available"`
}

type ApiSyncItem struct {
	Key                string `json:"key"`
	Id                 int64  `json:"id"`
	Path               string `json:"path"`
	Method             string `json:"method"`
	ApiGroup           string `json:"apiGroup"`
	Description        string `json:"description"`
	CurrentApiGroup    string `json:"currentApiGroup"`
	CurrentDescription string `json:"currentDescription"`
}

type ApplyApiSyncRequest struct {
	Version string   `json:"version"`
	Keys    []string `json:"keys"`
}

type ApplyApiSyncResponse struct {
	Added   int64 `json:"added"`
	Updated int64 `json:"updated"`
}

type ApplyPermissionRollbackRequest struct {
	ID               int64  `json:"id"`
	ExpectedRevision string `json:"expectedRevision"`
	Version          string `json:"version"`
}

type AuditLog struct {
	ID          int64  `json:"id"`
	ActorID     int64  `json:"actorId"`
	ActorName   string `json:"actorName"`
	AuthorityId int64  `json:"authorityId"`
	Module      string `json:"module"`
	Action      string `json:"action"`
	Object      string `json:"object"`
	Path        string `json:"path"`
	Method      string `json:"method"`
	Result      string `json:"result"`
	StatusCode  int64  `json:"statusCode"`
	IP          string `json:"ip"`
	TraceID     string `json:"traceId"`
	DurationMs  int64  `json:"durationMs"`
	Params      string `json:"params"`
	CreatedAt   string `json:"createdAt"`
	EventType   string `json:"eventType"`
}

type CasbinInfo struct {
	Path   string `json:"path"`   // 路径
	Method string `json:"method"` // 方法
}

type ChangePasswordRequest struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type CreateAgentRunRequest struct {
	ConversationId string `json:"conversationId,optional"`
	RequestId      string `json:"requestId"`
	Message        string `json:"message"`
}

type CreateApiRequest struct {
	SysApi
}

type CreateAuthorityRequest struct {
	SysAuthority
}

type CreateAuthorityResponse struct {
	SysAuthority SysAuthority `json:"sysAuthority"`
}

type CreateSysDictionaryInfoRequest struct {
	SysDictionaryInfo
}

type CreateSysDictionaryRequest struct {
	SysDictionary
}

type DeleteApiRequest struct {
	SysApi
}

type DeleteApisByIdsRequest struct {
	Ids []int64 `json:"ids,optional" form:"ids,optional"`
}

type DeleteAuthorityRequest struct {
	ID int64 `json:"id"`
}

type DeleteBaseMenuRequest struct {
	ID int64 `json:"id"`
}

type DeleteSysDictionaryInfoRequest struct {
	ID int64 `json:"id"`
}

type DeleteSysDictionaryRequest struct {
	ID int64 `json:"id"`
}

type DeleteUserRequest struct {
	UserID int64 `json:"userId"`
}

type Department struct {
	Id       int64        `json:"id,optional"`
	ParentId int64        `json:"parentId"`
	Name     string       `json:"name"`
	Code     string       `json:"code"`
	Sort     int64        `json:"sort,optional"`
	Status   int64        `json:"status"`
	Leader   string       `json:"leader,optional"`
	Children []Department `json:"children,optional"`
}

type DepartmentListResponse struct {
	List []Department `json:"list"`
}

type DeviceSession struct {
	Id        string `json:"id"`
	UserId    int64  `json:"userId"`
	Username  string `json:"username"`
	Ip        string `json:"ip"`
	UserAgent string `json:"userAgent"`
	CreatedAt string `json:"createdAt"`
	ExpiresAt string `json:"expiresAt"`
	Current   bool   `json:"current"`
}

type DeviceSessionListRequest struct {
	PageRequest
}

type DeviceSessionListResponse struct {
	List []DeviceSession `json:"list"`
	PageResponse
}

type FileIDRequest struct {
	Id int64 `json:"id"`
}

type FileListRequest struct {
	PageRequest
	Name   string `form:"name,optional"`
	Status string `form:"status,optional"`
}

type FileListResponse struct {
	List []FileResource `json:"list"`
	PageResponse
}

type FileReferenceRequest struct {
	FileId     int64  `json:"fileId"`
	ObjectType string `json:"objectType"`
	ObjectId   string `json:"objectId"`
}

type FileResource struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Mime         string `json:"mime"`
	Size         int64  `json:"size"`
	OwnerId      int64  `json:"ownerId"`
	DepartmentId int64  `json:"departmentId"`
	Visibility   string `json:"visibility"`
	Status       string `json:"status"`
	References   int64  `json:"references"`
	CreatedAt    string `json:"createdAt"`
}

type FileURLRequest struct {
	Id int64 `form:"id"`
}

type FileURLResponse struct {
	Url       string `json:"url"`
	ExpiresIn int64  `json:"expiresIn"`
}

type GetAllApiListRequest struct {
}

type GetAllApiListResponse struct {
	ApiList []SysApi `json:"apiList"`
}

type GetApiListRequest struct {
	OrderKey     string `form:"orderKey,optional"`     // 排序的字段
	Desc         bool   `form:"desc,optional"`         // 排序方式:升序false(默认) | 降序true
	DictIdMethod int64  `form:"dictIdMethod,optional"` // 字典info 的id
	Path         string `form:"path,optional"`
	Description  string `form:"description,optional"`
	ApiGroup     string `form:"apiGroup,optional"`
	Method       string `form:"method,optional"`
	PageRequest
}

type GetApiListResponse struct {
	List []SysApi `json:"list"`
	PageResponse
}

type GetAuditLogListRequest struct {
	PageRequest
	EventType string `form:"eventType,optional"`
	Module    string `form:"module,optional"`
	ActorId   int64  `form:"actorId,optional"`
	ActorName string `form:"actorName,optional"`
	Result    string `form:"result,optional"`
	StartTime string `form:"startTime,optional"`
	EndTime   string `form:"endTime,optional"`
}

type GetAuditLogListResponse struct {
	List []AuditLog `json:"list"`
	PageResponse
}

type GetAuthorityButtonsRequest struct {
	AuthorityId int64 `form:"authorityId"`
}

type GetAuthorityButtonsResponse struct {
	Revision   string  `json:"revision"`
	MenuBtnIds []int64 `json:"menuBtnIds"`
}

type GetAuthorityListRequest struct {
	PageRequest
}

type GetAuthorityListResponse struct {
	List []SysAuthority `json:"list"`
	PageResponse
}

type GetBaseMenuByIdRequest struct {
	Id int64 `form:"id"`
}

type GetBaseMenuByIdResponse struct {
	SysBaseMenu SysBaseMenu `json:"sysBaseMenu"`
}

type GetBaseMenuTreeRequest struct {
}

type GetBaseMenuTreeResponse struct {
	SysBaseMenuList []SysBaseMenu `json:"list"`
}

type GetMenuAuthorityRequest struct {
	AuthorityId int64 `form:"authorityId"`
}

type GetMenuAuthorityResponse struct {
	Revision    string    `json:"revision"`
	SysMenuList []SysMenu `json:"list"`
}

type GetMenuListRequest struct {
	PageRequest
}

type GetMenuListResponse struct {
	List []SysBaseMenu `json:"list"`
	PageResponse
}

type GetMenuRequest struct {
}

type GetMenuResponse struct {
	Menus []SysMenu `json:"menus"`
}

type GetPathByAuthorityIdRequest struct {
	AuthorityId int64 `form:"authorityId"`
}

type GetPathByAuthorityIdResponse struct {
	Revision string       `json:"revision"`
	List     []CasbinInfo `json:"list"`
}

type GetPermissionEditRequest struct {
	AuthorityId int64  `form:"authorityId"`
	Kind        string `form:"kind"`
}

type GetPermissionEditResponse struct {
	Revision    string        `json:"revision"`
	AuthorityId int64         `json:"authorityId"`
	Kind        string        `json:"kind"`
	Menus       []SysBaseMenu `json:"menus"`
	Apis        []SysApi      `json:"apis"`
	Departments []Department  `json:"departments"`
	MenuIds     []int64       `json:"menuIds"`
	MenuBtnIds  []int64       `json:"menuBtnIds"`
	Policies    []CasbinInfo  `json:"policies"`
	DataScope   RoleDataScope `json:"dataScope"`
}

type GetPermissionHistoryRequest struct {
	AuthorityId int64  `form:"authorityId"`
	Kind        string `form:"kind,optional"`
	PageRequest
}

type GetPermissionHistoryResponse struct {
	List  []PermissionChange `json:"list"`
	Total int64              `json:"total"`
}

type GetPermissionSnapshotRequest struct {
}

type GetPermissionSnapshotResponse struct {
	Revision      string    `json:"revision"`
	Fingerprint   string    `json:"fingerprint"`
	AuthorityId   int64     `json:"authorityId"`
	DefaultRouter string    `json:"defaultRouter"`
	Menus         []SysMenu `json:"menus"`
	Codes         []string  `json:"codes"`
}

type GetRoleDataScopeRequest struct {
	AuthorityId int64 `form:"authorityId"`
}

type GetSysDictionaryDetailsRequest struct {
	ID     int64  `form:"id,optional"`
	Type   string `form:"type,optional"`   // 字典名（英）
	Status int64  `form:"status,optional"` // 状态 1开启 2关闭
}

type GetSysDictionaryDetailsResponse struct {
	SysDictionary
}

type GetSysDictionaryInfoListDetailsByIdRequest struct {
	ID int64 `form:"id"`
}

type GetSysDictionaryInfoListDetailsByIdResponse struct {
	SysDictionaryInfo
}

type GetSysDictionaryInfoListRequest struct {
	Label           string `form:"label,optional"`
	Value           *int64 `form:"value,optional"`
	Status          int64  `form:"status,optional"`
	SysDictionaryID int64  `form:"sysDictionaryID"`
	PageRequest
}

type GetSysDictionaryInfoListResponse struct {
	List []SysDictionaryInfo `json:"list"`
	PageResponse
}

type GetSysDictionaryListRequest struct {
}

type GetSysDictionaryListResponse struct {
	List []SysDictionary `json:"list"`
}

type GetUserListRequest struct {
	PageRequest
}

type GetUserListResponse struct {
	List []UserInfo `json:"list"`
	PageResponse
}

type LoginRequest struct {
	UserName  string `json:"username"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type LoginResponse struct {
	AccessExpire int64    `json:"accessExpire"`
	AccessToken  string   `json:"accessToken"`
	UserInfo     UserInfo `json:"userInfo"`
}

type LogoutRequest struct {
}

type MeRequest struct {
}

type Membership struct {
	UserId       int64   `json:"userId"`
	DepartmentId int64   `json:"departmentId"`
	PositionIds  []int64 `json:"positionIds"`
}

type MessageResponse struct {
	Message string `json:"message"`
}

type Meta struct {
	ActiveName  string `json:"activeName,optional"`
	KeepAlive   bool   `json:"keepAlive,optional"`   // 是否缓存
	DefaultMenu bool   `json:"defaultMenu,optional"` // 是否是基础路由（开发中）
	Title       string `json:"title"`                // 菜单名
	Icon        string `json:"icon"`                 // 菜单图标
	CloseTab    bool   `json:"closeTab"`             // 自动关闭tab
}

type Model struct {
	ID        int64  `json:"ID,optional"`
	CreatedAt string `json:"CreatedAt,optional"`
	UpdatedAt string `json:"UpdatedAt,optional"`
	DeletedAt string `json:"DeletedAt,optional"`
}

type OrganizationIDRequest struct {
	Id int64 `json:"id"`
}

type OrganizationListRequest struct {
	Keyword string `form:"keyword,optional"`
	Status  int64  `form:"status,optional"`
}

type OrganizationUserRequest struct {
	UserId int64 `form:"userId"`
}

type PageRequest struct {
	PageNo   int64  `form:"pageNo,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
}

type PageResponse struct {
	Total    int64 `json:"total"`
	PageNo   int64 `json:"page"`
	PageSize int64 `json:"pageSize"`
}

type PermissionChange struct {
	ID             int64              `json:"id"`
	AuthorityId    int64              `json:"authorityId"`
	Kind           string             `json:"kind"`
	BeforeRevision string             `json:"beforeRevision"`
	AfterRevision  string             `json:"afterRevision"`
	Before         PermissionGrantSet `json:"before"`
	After          PermissionGrantSet `json:"after"`
	ActorId        int64              `json:"actorId"`
	ActorName      string             `json:"actorName"`
	TraceId        string             `json:"traceId"`
	CreatedAt      string             `json:"createdAt"`
}

type PermissionGrantSet struct {
	MenuIds    []int64       `json:"menuIds"`
	MenuBtnIds []int64       `json:"menuBtnIds"`
	Policies   []CasbinInfo  `json:"policies"`
	DataScope  RoleDataScope `json:"dataScope"`
}

type PermissionMenuLink struct {
	AuthorityId int64 `json:"authorityId"`
	MenuId      int64 `json:"menuId"`
}

type Position struct {
	Id     int64  `json:"id,optional"`
	Name   string `json:"name"`
	Code   string `json:"code"`
	Sort   int64  `json:"sort,optional"`
	Status int64  `json:"status"`
}

type PositionListResponse struct {
	List []Position `json:"list"`
}

type PreviewApiSyncResponse struct {
	Version  string        `json:"version"`
	Added    []ApiSyncItem `json:"added"`
	Changed  []ApiSyncItem `json:"changed"`
	Obsolete []ApiSyncItem `json:"obsolete"`
}

type PreviewMenuMoveRequest struct {
	ID       int64 `json:"id"`
	ParentId int64 `json:"parentId"`
}

type PreviewMenuMoveResponse struct {
	Version      string               `json:"version"`
	AuthorityIds []int64              `json:"authorityIds"`
	AncestorIds  []int64              `json:"ancestorIds"`
	AddedLinks   []PermissionMenuLink `json:"addedLinks"`
}

type PreviewPermissionRollbackRequest struct {
	ID int64 `json:"id"`
}

type PreviewPermissionRollbackResponse struct {
	Version string           `json:"version"`
	Change  PermissionChange `json:"change"`
	Allowed bool             `json:"allowed"`
	Reason  string           `json:"reason"`
}

type RandomImageRequest struct {
}

type RandomImageResponse struct {
	CaptchaImg string `json:"captchaImg"`
	CaptchaId  string `json:"captchaId"`
}

type RegisterRequest struct {
	Username     string  `json:"userName"`           // 用户名
	Password     string  `json:"passWord"`           // 密码
	NickName     string  `json:"nickName"`           // 昵称
	HeaderImg    string  `json:"headerImg,optional"` // 头像链接
	AuthorityId  int64   `json:"authorityId"`        // 角色id int64
	Enable       int64   `json:"enable,optional"`    // 是否启用
	AuthorityIds []int64 `json:"authorityIds"`       // 角色id []int64
	Phone        string  `json:"phone,optional"`     // 电话号码
	Email        string  `json:"email,optional"`     // 电子邮箱
}

type RegisterResponse struct {
}

type ResetUserPasswordRequest struct {
	UserID int64 `json:"userId"`
}

type RevokeDeviceSessionRequest struct {
	Id string `json:"id"`
}

type RoleDataScope struct {
	Revision         string  `json:"revision,optional"`
	ExpectedRevision string  `json:"expectedRevision,optional"`
	AuthorityId      int64   `json:"authorityId"`
	Scope            string  `json:"scope"`
	DepartmentIds    []int64 `json:"departmentIds"`
}

type SendEmailCodeRequest struct {
	Email   string `json:"email"`
	IsForce bool   `json:"isForce,optional"`
}

type SysApi struct {
	Path        string `json:"path,optional" form:"path,optional"`               // api路径
	Description string `json:"description,optional" form:"description,optional"` // api中文描述
	ApiGroup    string `json:"apiGroup,optional" form:"apiGroup,optional"`       // api组
	Method      string `json:"method,optional" form:"method,optional"`           // 方法:创建POST(默认)|查看GET|更新PUT|删除DELETE
	Model
}

type SysAuthority struct {
	AuthorityId     int64           `json:"authorityId,optional"` // 角色ID
	AuthorityName   string          `json:"authorityName"`        // 角色名
	ParentId        *int64          `json:"parentId"`             // 父角色ID
	DataAuthorityId []*SysAuthority `json:"dataAuthorityId,optional"`
	Children        []SysAuthority  `json:"children,optional"`
	SysBaseMenus    []SysBaseMenu   `json:"menus,optional"`
	DefaultRouter   string          `json:"defaultRouter,optional"` // 默认菜单(默认dashboard)
	ShowMenuIds     string          `json:"showMenuIds,optional"`
	CreatedAt       string          `json:"CreatedAt,optional"` // 创建时间
	UpdatedAt       string          `json:"UpdatedAt,optional"` // 更新时间
	DeletedAt       string          `json:"DeletedAt,optional"`
}

type SysBaseMenu struct {
	MenuLevel     int64                  `json:"-"`
	ParentId      int64                  `json:"parentId"`      // 父菜单ID
	Path          string                 `json:"path"`          // 路由path
	Name          string                 `json:"name"`          // 路由name
	Hidden        bool                   `json:"hidden"`        // 是否在列表隐藏
	Component     string                 `json:"component"`     // 对应前端文件路径
	Sort          int64                  `json:"sort,optional"` // 排序标记
	SysAuthoritys []SysAuthority         `json:"authoritys,optional"`
	Children      []SysBaseMenu          `json:"children,optional"`
	Parameters    []SysBaseMenuParameter `json:"parameters"`
	MenuBtn       []SysBaseMenuBtn       `json:"menuBtn"`
	Meta          Meta                   `json:"meta"`
	Model
}

type SysBaseMenuBtn struct {
	PermissionKey string `json:"permissionKey,optional"`
	Name          string `json:"name"`
	Desc          string `json:"desc"`
	SysBaseMenuID int64  `json:"sysBaseMenuID,optional"`
	Model
}

type SysBaseMenuParameter struct {
	SysBaseMenuID int64  `json:"sysBaseMenuId,optional"`
	Type          string `json:"type"`  // 地址栏携带参数为params还是query
	Key           string `json:"key"`   // 地址栏携带参数的key
	Value         string `json:"value"` // 地址栏携带参数的值
	Model
}

type SysDictionary struct {
	Model
	Name                  string              `json:"name"`            // 字典名（中）
	Type                  string              `json:"type"`            // 字典名（英）
	Status                int64               `json:"status,optional"` // 状态 1开启 2关闭 默认1
	Desc                  string              `json:"desc"`            // 描述
	SysDictionaryInfoList []SysDictionaryInfo `json:"sysDictionaryInfoList,optional"`
}

type SysDictionaryInfo struct {
	Model
	Label           string `json:"label,optional" form:"label,optional"`                     // 展示值
	Value           int64  `json:"value,optional" form:"value,optional"`                     // 字典值
	Extend          string `json:"extend,optional" form:"extend,optional"`                   // 扩展值
	Status          int64  `json:"status,optional" form:"status,optional"`                   // 启用状态 1开启 2关闭
	Sort            int64  `json:"sort,optional" form:"sort,optional"`                       // 排序标记
	SysDictionaryID int64  `json:"sysDictionaryID,optional" form:"sysDictionaryID,optional"` // 关联标记
}

type SysMenu struct {
	SysBaseMenu
	MenuId      string                 `json:"menuId"`
	AuthorityId int64                  `json:"-" gorm:"comment:角色ID"`
	Children    []SysMenu              `json:"children"`
	Parameters  []SysBaseMenuParameter `json:"parameters"`
	Btns        map[string]int64       `json:"btns"`
}

type TransferUserResourcesRequest struct {
	UserID       int64 `json:"userId"`
	TargetUserID int64 `json:"targetUserId"`
	IncludeFiles bool  `json:"includeFiles"`
	IncludeAI    bool  `json:"includeAI"`
}

type TransferUserResourcesResponse struct {
	Files           int64  `json:"files"`
	AIConversations int64  `json:"aiConversations"`
	AIMessages      int64  `json:"aiMessages"`
	AIRuns          int64  `json:"aiRuns"`
	TransactionMode string `json:"transactionMode"`
}

type UpdateApiRequest struct {
	SysApi
}

type UpdateAuthorityButtonsRequest struct {
	ExpectedRevision string  `json:"expectedRevision"`
	AuthorityId      int64   `json:"authorityId"`
	MenuBtnIds       []int64 `json:"menuBtnIds"`
}

type UpdateAuthorityRequest struct {
	SysAuthority
}

type UpdateAuthorityResponse struct {
	SysAuthority SysAuthority `json:"sysAuthority"`
	Message      string       `json:"message"`
}

type UpdateBaseMenuRequest struct {
	MovePreviewVersion string `json:"movePreviewVersion,optional"`
	SysBaseMenu
}

type UpdateCasbinDataByApiIdsRequest struct {
	ExpectedRevision string  `json:"expectedRevision"`
	AuthorityId      int64   `json:"authorityId"`
	ApiIds           []int64 `json:"apiIds"`
}

type UpdateCasbinDataRequest struct {
	ExpectedRevision string       `json:"expectedRevision"`
	AuthorityId      int64        `json:"authorityId"`
	CasbinInfoList   []CasbinInfo `json:"casbinInfoList"`
}

type UpdateSysDictionaryInfoRequest struct {
	SysDictionaryInfo
}

type UpdateSysDictionaryRequest struct {
	SysDictionary
}

type UpdateUserInfoRequest struct {
	ID           int64   `json:"ID"`                    // 主键ID
	NickName     *string `json:"nickName,optional"`     // 用户昵称
	Phone        *string `json:"phone,optional"`        // 用户手机号
	AuthorityId  *int64  `json:"authorityId,optional"`  // 默认角色，必须属于关联角色
	AuthorityIds []int64 `json:"authorityIds,optional"` // 角色ID
	Email        *string `json:"email,optional"`        // 用户邮箱
	HeaderImg    *string `json:"headerImg,optional"`    // 用户头像
	SideMode     *string `json:"sideMode,optional"`     // 用户侧边主题
	Enable       *int64  `json:"enable,optional"`       //冻结用户
}

type UploadFileImgRequest struct {
	Visibility string `form:"visibility,optional"`
}

type UploadFileImgResponse struct {
	FileImgUrl string `json:"fileImgUrl"`
	FileId     int64  `json:"fileId"`
}

type UserInfo struct {
	UUID        string         `json:"uuid"`        // 用户UUID
	Username    string         `json:"userName"`    // 用户登录名
	Password    string         `json:"-"`           // 用户登录密码
	NickName    string         `json:"nickName"`    // 用户昵称
	SideMode    string         `json:"sideMode"`    // 用户侧边主题
	HeaderImg   string         `json:"headerImg"`   // 用户头像
	BaseColor   string         `json:"baseColor"`   // 基础颜色
	ActiveColor string         `json:"activeColor"` // 活跃颜色
	AuthorityId int64          `json:"authorityId"` // 用户角色ID
	Authority   SysAuthority   `json:"authority"`
	Authorities []SysAuthority `json:"authorities"`
	Phone       string         `json:"phone"`  // 用户手机号
	Email       string         `json:"email"`  // 用户邮箱
	Enable      int64          `json:"enable"` //用户是否被冻结 1正常 2冻结
	Model
}

type UserResourcePreviewRequest struct {
	UserID int64 `form:"userId"`
}

type UserResourcePreviewResponse struct {
	UserID          int64  `json:"userId"`
	Username        string `json:"username"`
	Files           int64  `json:"files"`
	AIConversations int64  `json:"aiConversations"`
	AIMessages      int64  `json:"aiMessages"`
	AIRuns          int64  `json:"aiRuns"`
	AIAvailable     bool   `json:"aiAvailable"`
	AIReason        string `json:"aiReason"`
	TransferMode    string `json:"transferMode"`
}
