// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package server

import (
	"context"

	"go-zero-admin/application/applet/rpc/internal/logic/organization"
	"go-zero-admin/application/applet/rpc/internal/svc"
	"go-zero-admin/application/applet/rpc/pb"
)

type OrganizationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrganizationServer
}

func NewOrganizationServer(svcCtx *svc.ServiceContext) *OrganizationServer {
	return &OrganizationServer{
		svcCtx: svcCtx,
	}
}

func (s *OrganizationServer) GetDepartmentTree(ctx context.Context, in *pb.OrganizationListRequest) (*pb.DepartmentListResponse, error) {
	l := organizationlogic.NewGetDepartmentTreeLogic(ctx, s.svcCtx)
	return l.GetDepartmentTree(in)
}

func (s *OrganizationServer) CreateDepartment(ctx context.Context, in *pb.DepartmentRequest) (*pb.Department, error) {
	l := organizationlogic.NewCreateDepartmentLogic(ctx, s.svcCtx)
	return l.CreateDepartment(in)
}

func (s *OrganizationServer) UpdateDepartment(ctx context.Context, in *pb.DepartmentRequest) (*pb.NoDataResponse, error) {
	l := organizationlogic.NewUpdateDepartmentLogic(ctx, s.svcCtx)
	return l.UpdateDepartment(in)
}

func (s *OrganizationServer) DeleteDepartment(ctx context.Context, in *pb.OrganizationIDRequest) (*pb.NoDataResponse, error) {
	l := organizationlogic.NewDeleteDepartmentLogic(ctx, s.svcCtx)
	return l.DeleteDepartment(in)
}

func (s *OrganizationServer) GetPositionList(ctx context.Context, in *pb.OrganizationListRequest) (*pb.PositionListResponse, error) {
	l := organizationlogic.NewGetPositionListLogic(ctx, s.svcCtx)
	return l.GetPositionList(in)
}

func (s *OrganizationServer) CreatePosition(ctx context.Context, in *pb.PositionRequest) (*pb.Position, error) {
	l := organizationlogic.NewCreatePositionLogic(ctx, s.svcCtx)
	return l.CreatePosition(in)
}

func (s *OrganizationServer) UpdatePosition(ctx context.Context, in *pb.PositionRequest) (*pb.NoDataResponse, error) {
	l := organizationlogic.NewUpdatePositionLogic(ctx, s.svcCtx)
	return l.UpdatePosition(in)
}

func (s *OrganizationServer) DeletePosition(ctx context.Context, in *pb.OrganizationIDRequest) (*pb.NoDataResponse, error) {
	l := organizationlogic.NewDeletePositionLogic(ctx, s.svcCtx)
	return l.DeletePosition(in)
}

func (s *OrganizationServer) GetMembership(ctx context.Context, in *pb.OrganizationIDRequest) (*pb.MembershipResponse, error) {
	l := organizationlogic.NewGetMembershipLogic(ctx, s.svcCtx)
	return l.GetMembership(in)
}

func (s *OrganizationServer) UpdateMembership(ctx context.Context, in *pb.MembershipRequest) (*pb.NoDataResponse, error) {
	l := organizationlogic.NewUpdateMembershipLogic(ctx, s.svcCtx)
	return l.UpdateMembership(in)
}

func (s *OrganizationServer) GetRoleDataScope(ctx context.Context, in *pb.GetRoleDataScopeRequest) (*pb.RoleDataScopeResponse, error) {
	l := organizationlogic.NewGetRoleDataScopeLogic(ctx, s.svcCtx)
	return l.GetRoleDataScope(in)
}

func (s *OrganizationServer) UpdateRoleDataScope(ctx context.Context, in *pb.RoleDataScopeRequest) (*pb.NoDataResponse, error) {
	l := organizationlogic.NewUpdateRoleDataScopeLogic(ctx, s.svcCtx)
	return l.UpdateRoleDataScope(in)
}
