// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: applet.proto

package sessionmanage

import (
	"context"

	"go-zero-admin/application/applet/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeviceSession              = pb.DeviceSession
	DeviceSessionListRequest   = pb.DeviceSessionListRequest
	DeviceSessionListResponse  = pb.DeviceSessionListResponse
	NoDataResponse             = pb.NoDataResponse
	PageRequest                = pb.PageRequest
	RevokeDeviceSessionRequest = pb.RevokeDeviceSessionRequest
	SessionRequest             = pb.SessionRequest

	SessionManage interface {
		GetDeviceSessions(ctx context.Context, in *DeviceSessionListRequest, opts ...grpc.CallOption) (*DeviceSessionListResponse, error)
		RevokeDeviceSession(ctx context.Context, in *RevokeDeviceSessionRequest, opts ...grpc.CallOption) (*NoDataResponse, error)
	}

	defaultSessionManage struct {
		cli zrpc.Client
	}
)

func NewSessionManage(cli zrpc.Client) SessionManage {
	return &defaultSessionManage{
		cli: cli,
	}
}

func (m *defaultSessionManage) GetDeviceSessions(ctx context.Context, in *DeviceSessionListRequest, opts ...grpc.CallOption) (*DeviceSessionListResponse, error) {
	client := pb.NewSessionManageClient(m.cli.Conn())
	return client.GetDeviceSessions(ctx, in, opts...)
}

func (m *defaultSessionManage) RevokeDeviceSession(ctx context.Context, in *RevokeDeviceSessionRequest, opts ...grpc.CallOption) (*NoDataResponse, error) {
	client := pb.NewSessionManageClient(m.cli.Conn())
	return client.RevokeDeviceSession(ctx, in, opts...)
}
